export type CaseStudyContent = {
  badge: string
  client: string
  title: string
  desc: string
  duration: string
  servicesProvided: string[]
  heroImage: string
  challengeHeading: string
  challenge: string
  solutionHeading: string
  solution: string
  overviewHeading: string
  overview: string
  approachHeading: string
  approach: { title: string; desc: string }[]
  keyFeaturesHeading: string
  keyFeatures: { title: string; bullets: string[] }[]
  backLabel: string
  servicesLabel: string
}

export type CaseStudy = {
  slug: string
  industryTag: string
  result: string
  year: string
  th: CaseStudyContent
  en: CaseStudyContent
}

export const caseStudies: CaseStudy[] = [
  {
    slug: 'savelberg',
    industryTag: 'F&B',
    result: 'เว็บไซต์ใหม่',
    year: '2025',
    th: {
      badge: 'F&B',
      client: 'Savelberg Restaurant',
      title: 'เว็บไซต์ร้านอาหารระดับมิชลินสตาร์ Savelberg',
      desc: 'ออกแบบและพัฒนาเว็บไซต์ให้ร้านอาหารไฟน์ไดนิ่งสไตล์ฝรั่งเศสระดับมิชลินสตาร์ พร้อมวางกลยุทธ์คอนเทนต์และการตลาดดิจิทัล เพื่อสื่อสารความประณีตของแบรนด์ให้ลูกค้าทั้งชาวไทยและต่างชาติ',
      duration: '3 เดือน',
      servicesProvided: ['ออกแบบเว็บไซต์ (UX/UI)', 'พัฒนาเว็บไซต์', 'กำกับทิศทางภาพถ่าย & คอนเทนต์', 'ช่วยวางกลยุทธ์การตลาดดิจิทัล', 'แชทบอท AI ตอบคำถามลูกค้า'],
      heroImage: '/images/case-studies/savelberg/cover.png',
      challengeHeading: 'โจทย์ของโปรเจกต์',
      challenge: 'Savelberg เป็นร้านอาหารฝรั่งเศสระดับมิชลินสตาร์ภายใต้การดูแลของเชฟ Henk Savelberg ต้องการเว็บไซต์ที่สื่อสารความประณีตและมาตรฐานระดับโลกของร้าน ให้สมกับภาพลักษณ์ไฟน์ไดนิ่ง ในขณะเดียวกันก็ต้องใช้งานง่าย ให้ลูกค้าทั้งคนไทยและนักท่องเที่ยวต่างชาติค้นหาข้อมูลเมนู จองโต๊ะ และรู้สึกถึงประสบการณ์ระดับพรีเมียมได้ตั้งแต่หน้าแรก',
      solutionHeading: 'แนวทางที่เราทำ',
      solution: 'เราออกแบบเว็บไซต์ใหม่ทั้งหมดด้วยโทนมืดหรูหราที่ขับเน้นภาพถ่ายอาหารและบรรยากาศร้าน วางโครงสร้างให้เข้าถึงเมนู การจองโต๊ะ และเรื่องราวของเชฟได้ในไม่กี่คลิก พร้อมซัพพอร์ตสองภาษา (ไทย/อังกฤษ) และวางแนวทางคอนเทนต์สำหรับช่องทางการตลาดออนไลน์ให้สอดคล้องกับงานออกแบบ',
      overviewHeading: 'ภาพรวมโปรเจกต์',
      overview: 'Savelberg ตั้งอยู่ย่านยานนาวา กรุงเทพฯ ชูจุดเด่นด้านอาหารฝรั่งเศสร่วมสมัยผสมผสานกลิ่นอายเมดิเตอร์เรเนียน จากเชฟที่ได้รับดาวมิชลินมาแล้วถึง 5 ร้าน โจทย์หลักคือทำให้เว็บไซต์เป็นหน้าด่านที่ถ่ายทอดมาตรฐานนี้ได้ทันทีที่เข้าชม',
      approachHeading: 'กระบวนการทำงาน',
      approach: [
        { title: 'ทำความเข้าใจแบรนด์', desc: 'ลงพื้นที่เก็บข้อมูลบรรยากาศร้าน สไตล์การเสิร์ฟ และตัวตนของเชฟ เพื่อแปลงเป็นโทนภาพและข้อความบนเว็บไซต์' },
        { title: 'ออกแบบ UX/UI', desc: 'วางโครงสร้างหน้าเว็บให้เมนู การจองโต๊ะ และแกลเลอรีภาพเข้าถึงง่าย เน้นภาพใหญ่และพื้นที่ว่างแบบไฟน์ไดนิ่ง' },
        { title: 'พัฒนาและเชื่อมระบบจอง', desc: 'พัฒนาเว็บไซต์ให้โหลดเร็ว รองรับสองภาษา และเชื่อมต่อช่องทางการจองโต๊ะออนไลน์' },
        { title: 'วางแผนคอนเทนต์การตลาด', desc: 'ช่วยวางแนวทางคอนเทนต์ภาพและข้อความสำหรับโซเชียลมีเดีย ให้สื่อสารตรงกับกลุ่มลูกค้าไฟน์ไดนิ่ง' },
      ],
      keyFeaturesHeading: 'ฟีเจอร์เด่น',
      keyFeatures: [
        {
          title: 'ประสบการณ์แบรนด์บนเว็บไซต์',
          bullets: [
            'ดีไซน์โทนมืดหรูหราที่เข้ากับภาพลักษณ์ไฟน์ไดนิ่ง',
            'แกลเลอรีภาพอาหารและบรรยากาศร้านความละเอียดสูง',
            'เรื่องราวของเชฟและความเป็นมาของร้าน',
          ],
        },
        {
          title: 'การจองโต๊ะที่ใช้งานง่าย',
          bullets: [
            'ระบบจองโต๊ะออนไลน์เชื่อมต่อโดยตรงจากเว็บไซต์',
            'แสดงเมนู Tasting Menu และไวน์ลิสต์อย่างเป็นระเบียบ',
            'รองรับสองภาษา ไทยและอังกฤษ',
          ],
        },
        {
          title: 'สนับสนุนด้านการตลาด',
          bullets: [
            'วางแนวทางคอนเทนต์สำหรับโซเชียลมีเดีย',
            'จัดระเบียบภาพถ่ายให้พร้อมใช้ในสื่อโฆษณา',
            'โครงสร้างเว็บไซต์ที่เอื้อต่อการทำ SEO ในระยะยาว',
            'แชทบอท AI ตอบคำถามเมนูและช่วยแนะนำการจองโต๊ะได้ตลอด 24 ชั่วโมง',
          ],
        },
      ],
      backLabel: 'กลับไปหน้า Case Studies',
      servicesLabel: 'บริการที่ให้',
    },
    en: {
      badge: 'F&B',
      client: 'Savelberg Restaurant',
      title: 'Savelberg — Michelin-Starred Restaurant Website',
      desc: 'Designed and built a new website for a Michelin-starred French fine-dining restaurant, with content direction and digital marketing support to carry the brand\'s refinement online for both Thai and international guests.',
      duration: '3 months',
      servicesProvided: ['UX/UI Design', 'Web Development', 'Photography & Content Direction', 'Digital Marketing Support', 'AI Concierge Chatbot'],
      heroImage: '/images/case-studies/savelberg/cover.png',
      challengeHeading: 'The Challenge',
      challenge: "Savelberg is a Michelin-starred French restaurant led by Chef Henk Savelberg. The brand needed a website that matched its fine-dining standard — elegant enough to reflect the quality of the food and service, yet simple enough for both local and international guests to browse the menu, reserve a table, and feel the premium experience from the very first scroll.",
      solutionHeading: 'Our Solution',
      solution: "We designed a new website in a dark, refined palette that lets the food and ambience photography carry the page. The structure puts the menu, reservations, and the chef's story within a few clicks, built bilingual for Thai and English, and paired with a content direction for the restaurant's marketing channels.",
      overviewHeading: 'Project Overview',
      overview: "Savelberg sits in Bangkok's Yan Nawa district, serving contemporary French cuisine with Mediterranean influences from a chef who has earned Michelin recognition across five previous restaurants. The core challenge was making the website communicate that standard the moment it loads.",
      approachHeading: 'Our Approach',
      approach: [
        { title: 'Brand Immersion', desc: "Spent time understanding the restaurant's ambience, service style, and the chef's story to translate into visual tone and website copy." },
        { title: 'UX/UI Design', desc: 'Structured the site so the menu, reservations, and photo gallery are easy to reach, with generous whitespace that reads as fine dining.' },
        { title: 'Development & Booking Integration', desc: 'Built a fast, bilingual website connected to an online table-reservation flow.' },
        { title: 'Marketing Content Direction', desc: "Planned a content direction for photography and copy across the restaurant's social channels." },
      ],
      keyFeaturesHeading: 'Key Features',
      keyFeatures: [
        {
          title: 'Brand Experience Online',
          bullets: [
            'Dark, elegant design language matching the fine-dining brand',
            'High-resolution gallery of dishes and restaurant ambience',
            "The chef's story and the restaurant's background",
          ],
        },
        {
          title: 'Effortless Reservations',
          bullets: [
            'Online table reservation connected directly from the website',
            'Tasting menu and wine list presented clearly',
            'Fully bilingual in Thai and English',
          ],
        },
        {
          title: 'Marketing Support',
          bullets: [
            'Content direction for social media channels',
            'Photography organized and ready for ad placements',
            'Site structure built with long-term SEO in mind',
          ],
        },
      ],
      backLabel: 'Back to Case Studies',
      servicesLabel: 'Services Provided',
    },
  },
  {
    slug: 'ovo',
    industryTag: 'F&B',
    result: 'เว็บไซต์ใหม่',
    year: '2025',
    th: {
      badge: 'F&B',
      client: 'OVO',
      title: 'เว็บไซต์แบรนด์ไอศกรีม OVO',
      desc: 'ออกแบบและพัฒนาเว็บไซต์ให้แบรนด์ไอศกรีมและของหวาน เน้นภาพถ่ายสไตล์อบอุ่นเป็นกันเอง พร้อมระบบสั่งซื้อออนไลน์และคอนเทนต์สำหรับโซเชียลมีเดีย',
      duration: '2 เดือน',
      servicesProvided: ['ออกแบบเว็บไซต์ (UX/UI)', 'พัฒนาเว็บไซต์', 'กำกับทิศทางภาพถ่าย & คอนเทนต์', 'ช่วยวางกลยุทธ์การตลาดดิจิทัล'],
      heroImage: '/images/case-studies/ovo/cover.png',
      challengeHeading: 'โจทย์ของโปรเจกต์',
      challenge: 'OVO เป็นแบรนด์ไอศกรีมและของหวานที่มีจุดแข็งด้านภาพลักษณ์อบอุ่น เป็นกันเอง แต่ยังไม่มีเว็บไซต์ที่สื่อสารตัวตนแบรนด์ได้ครบถ้วน ลูกค้าไม่สามารถดูเมนู สั่งซื้อ หรือหาข้อมูลร้านได้สะดวกจากช่องทางออนไลน์',
      solutionHeading: 'แนวทางที่เราทำ',
      solution: 'เราออกแบบเว็บไซต์โทนสว่าง อบอุ่น ให้ภาพถ่ายสินค้าเป็นพระเอก พร้อมวางระบบสั่งซื้อออนไลน์ที่ใช้งานง่าย และวางแนวทางคอนเทนต์ให้สอดคล้องกับโทนแบรนด์บนโซเชียลมีเดีย',
      overviewHeading: 'ภาพรวมโปรเจกต์',
      overview: 'OVO ต้องการเว็บไซต์ที่เป็นหน้าร้านออนไลน์หลัก ให้ลูกค้าดูเมนู สั่งซื้อ และรู้สึกถึงความเป็นกันเองของแบรนด์ได้ตั้งแต่เข้าชมครั้งแรก',
      approachHeading: 'กระบวนการทำงาน',
      approach: [
        { title: 'ทำความเข้าใจแบรนด์', desc: 'เก็บข้อมูลโทนภาพ สไตล์การสื่อสาร และกลุ่มลูกค้าเป้าหมายของแบรนด์' },
        { title: 'ออกแบบ UX/UI', desc: 'วางโครงสร้างหน้าเว็บให้เมนูและการสั่งซื้อเข้าถึงง่าย เน้นภาพสินค้าชัดเจน' },
        { title: 'พัฒนาและเชื่อมระบบสั่งซื้อ', desc: 'พัฒนาเว็บไซต์ให้โหลดเร็วและเชื่อมต่อช่องทางสั่งซื้อออนไลน์' },
        { title: 'วางแผนคอนเทนต์การตลาด', desc: 'วางแนวทางคอนเทนต์ภาพและข้อความสำหรับโซเชียลมีเดีย' },
      ],
      keyFeaturesHeading: 'ฟีเจอร์เด่น',
      keyFeatures: [
        { title: 'ประสบการณ์แบรนด์บนเว็บไซต์', bullets: ['ดีไซน์โทนสว่างอบอุ่นเข้ากับภาพลักษณ์แบรนด์', 'แกลเลอรีภาพสินค้าความละเอียดสูง', 'เรื่องราวความเป็นมาของแบรนด์'] },
        { title: 'สั่งซื้อออนไลน์สะดวก', bullets: ['ระบบสั่งซื้อออนไลน์เชื่อมต่อโดยตรงจากเว็บไซต์', 'แสดงเมนูสินค้าและราคาอย่างเป็นระเบียบ', 'รองรับการใช้งานบนมือถือเต็มรูปแบบ'] },
        { title: 'สนับสนุนด้านการตลาด', bullets: ['วางแนวทางคอนเทนต์สำหรับโซเชียลมีเดีย', 'จัดระเบียบภาพถ่ายให้พร้อมใช้ในสื่อโฆษณา', 'โครงสร้างเว็บไซต์ที่เอื้อต่อการทำ SEO ในระยะยาว'] },
      ],
      backLabel: 'กลับไปหน้า Case Studies',
      servicesLabel: 'บริการที่ให้',
    },
    en: {
      badge: 'F&B',
      client: 'OVO',
      title: 'OVO — Ice Cream Brand Website',
      desc: "Designed and built a website for an ice cream and dessert brand, with warm, approachable photography, an online ordering flow, and social media content direction.",
      duration: '2 months',
      servicesProvided: ['UX/UI Design', 'Web Development', 'Photography & Content Direction', 'Digital Marketing Support'],
      heroImage: '/images/case-studies/ovo/cover.png',
      challengeHeading: 'The Challenge',
      challenge: "OVO is an ice cream and dessert brand with a warm, approachable identity, but had no website that carried that identity online. Customers couldn't browse the menu, order, or find the shop's information through any online channel.",
      solutionHeading: 'Our Solution',
      solution: "We designed a bright, warm website that lets product photography lead, built an easy online ordering flow, and planned a content direction matching the brand's tone across social channels.",
      overviewHeading: 'Project Overview',
      overview: "OVO needed its website to work as a primary online storefront — letting customers browse the menu, order, and feel the brand's warmth from the first visit.",
      approachHeading: 'Our Approach',
      approach: [
        { title: 'Brand Immersion', desc: "Gathered the brand's visual tone, communication style, and target audience." },
        { title: 'UX/UI Design', desc: 'Structured the site so the menu and ordering flow are easy to reach, with clear product photography.' },
        { title: 'Development & Ordering Integration', desc: 'Built a fast website connected to an online ordering flow.' },
        { title: 'Marketing Content Direction', desc: 'Planned a content direction for photography and copy across social channels.' },
      ],
      keyFeaturesHeading: 'Key Features',
      keyFeatures: [
        { title: 'Brand Experience Online', bullets: ['Bright, warm design language matching the brand', 'High-resolution gallery of products', "The brand's story and background"] },
        { title: 'Effortless Online Ordering', bullets: ['Online ordering connected directly from the website', 'Menu and pricing presented clearly', 'Fully responsive on mobile'] },
        { title: 'Marketing Support', bullets: ['Content direction for social media channels', 'Photography organized and ready for ad placements', 'Site structure built with long-term SEO in mind'] },
      ],
      backLabel: 'Back to Case Studies',
      servicesLabel: 'Services Provided',
    },
  },
  {
    slug: 'base',
    industryTag: 'Fitness & Wellness',
    result: 'เว็บไซต์ใหม่',
    year: '2025',
    th: {
      badge: 'Fitness & Wellness',
      client: 'BASE',
      title: 'เว็บไซต์สตูดิโอฟิตเนส BASE',
      desc: 'ออกแบบและพัฒนาเว็บไซต์ให้สตูดิโอฟิตเนสและเวลเนส พร้อมระบบจองคลาสออนไลน์และแนะนำเทรนเนอร์ เพื่อให้สมาชิกใหม่ตัดสินใจสมัครได้ง่ายขึ้น',
      duration: '2 เดือน',
      servicesProvided: ['ออกแบบเว็บไซต์ (UX/UI)', 'พัฒนาเว็บไซต์', 'ระบบจองคลาสออนไลน์', 'กำกับทิศทางภาพถ่าย & คอนเทนต์'],
      heroImage: '/images/case-studies/base/cover.png',
      challengeHeading: 'โจทย์ของโปรเจกต์',
      challenge: 'BASE เป็นสตูดิโอฟิตเนสที่เน้นการดูแลสุขภาพแบบองค์รวม มีทีมเทรนเนอร์และอุปกรณ์ที่ทันสมัย แต่เว็บไซต์เดิมไม่สามารถสื่อสารความเป็นมืออาชีพและไม่มีช่องทางให้ลูกค้าใหม่จองคลาสทดลองได้สะดวก',
      solutionHeading: 'แนวทางที่เราทำ',
      solution: 'เราออกแบบเว็บไซต์โทนมืดดูทันสมัย เน้นภาพเทรนเนอร์และบรรยากาศสตูดิโอ พร้อมระบบจองคลาสออนไลน์ที่ใช้งานง่าย ให้ลูกค้าใหม่ตัดสินใจสมัครได้ไวขึ้น',
      overviewHeading: 'ภาพรวมโปรเจกต์',
      overview: 'BASE ต้องการเว็บไซต์ที่สื่อสารความเป็นมืออาชีพของทีมเทรนเนอร์ และลดขั้นตอนการจองคลาสทดลองสำหรับลูกค้าใหม่',
      approachHeading: 'กระบวนการทำงาน',
      approach: [
        { title: 'ทำความเข้าใจแบรนด์', desc: 'เก็บข้อมูลบรรยากาศสตูดิโอ ทีมเทรนเนอร์ และกลุ่มลูกค้าเป้าหมาย' },
        { title: 'ออกแบบ UX/UI', desc: 'วางโครงสร้างหน้าเว็บให้คลาสและเทรนเนอร์เข้าถึงง่าย พร้อมพื้นที่ให้ภาพเคลื่อนไหว' },
        { title: 'พัฒนาและเชื่อมระบบจอง', desc: 'พัฒนาเว็บไซต์ให้โหลดเร็วและเชื่อมต่อระบบจองคลาสออนไลน์' },
        { title: 'วางแผนคอนเทนต์', desc: 'วางแนวทางคอนเทนต์ภาพและข้อความสำหรับโซเชียลมีเดีย' },
      ],
      keyFeaturesHeading: 'ฟีเจอร์เด่น',
      keyFeatures: [
        { title: 'ประสบการณ์แบรนด์บนเว็บไซต์', bullets: ['ดีไซน์โทนมืดทันสมัยเข้ากับภาพลักษณ์ฟิตเนส', 'แกลเลอรีภาพเทรนเนอร์และอุปกรณ์', 'โปรไฟล์เทรนเนอร์แต่ละคน'] },
        { title: 'จองคลาสที่ใช้งานง่าย', bullets: ['ระบบจองคลาสออนไลน์เชื่อมต่อโดยตรงจากเว็บไซต์', 'แสดงตารางคลาสและความพร้อมของเทรนเนอร์', 'รองรับการใช้งานบนมือถือเต็มรูปแบบ'] },
        { title: 'สนับสนุนด้านการตลาด', bullets: ['วางแนวทางคอนเทนต์สำหรับโซเชียลมีเดีย', 'จัดระเบียบภาพถ่ายให้พร้อมใช้ในสื่อโฆษณา', 'โครงสร้างเว็บไซต์ที่เอื้อต่อการทำ SEO ในระยะยาว'] },
      ],
      backLabel: 'กลับไปหน้า Case Studies',
      servicesLabel: 'บริการที่ให้',
    },
    en: {
      badge: 'Fitness & Wellness',
      client: 'BASE',
      title: 'BASE — Fitness Studio Website',
      desc: 'Designed and built a website for a fitness and wellness studio, with an online class-booking flow and trainer profiles to help new members decide and sign up faster.',
      duration: '2 months',
      servicesProvided: ['UX/UI Design', 'Web Development', 'Class Booking System', 'Photography & Content Direction'],
      heroImage: '/images/case-studies/base/cover.png',
      challengeHeading: 'The Challenge',
      challenge: "BASE is a fitness studio focused on holistic wellness, with a strong trainer team and modern equipment, but its old website couldn't communicate that professionalism and gave new customers no easy way to book a trial class.",
      solutionHeading: 'Our Solution',
      solution: "We designed a modern, dark-toned website that lets trainer and studio photography lead, with an easy online class-booking flow so new customers can sign up faster.",
      overviewHeading: 'Project Overview',
      overview: "BASE needed a website that communicated its trainer team's professionalism and removed friction from booking a trial class for new customers.",
      approachHeading: 'Our Approach',
      approach: [
        { title: 'Brand Immersion', desc: "Gathered the studio's ambience, trainer team, and target audience." },
        { title: 'UX/UI Design', desc: 'Structured the site so classes and trainers are easy to reach, with room for dynamic photography.' },
        { title: 'Development & Booking Integration', desc: 'Built a fast website connected to an online class-booking system.' },
        { title: 'Content Direction', desc: 'Planned a content direction for photography and copy across social channels.' },
      ],
      keyFeaturesHeading: 'Key Features',
      keyFeatures: [
        { title: 'Brand Experience Online', bullets: ['Modern, dark design language matching the fitness brand', 'Gallery of trainers and equipment', 'Individual trainer profiles'] },
        { title: 'Effortless Class Booking', bullets: ['Online class booking connected directly from the website', 'Class schedule and trainer availability shown clearly', 'Fully responsive on mobile'] },
        { title: 'Marketing Support', bullets: ['Content direction for social media channels', 'Photography organized and ready for ad placements', 'Site structure built with long-term SEO in mind'] },
      ],
      backLabel: 'Back to Case Studies',
      servicesLabel: 'Services Provided',
    },
  },
  {
    slug: 'blue-bear',
    industryTag: 'Apparel & Uniforms',
    result: 'เว็บไซต์ใหม่',
    year: '2025',
    th: {
      badge: 'Apparel & Uniforms',
      client: 'Blue Bear',
      title: 'เว็บไซต์ผู้ผลิตชุดยูนิฟอร์มทางการแพทย์ Blue Bear',
      desc: 'ออกแบบและพัฒนาเว็บไซต์ให้ผู้ผลิตชุดยูนิฟอร์มทางการแพทย์ พร้อมแคตตาล็อกสินค้าและระบบติดต่อสั่งซื้อแบบองค์กร เพื่อรองรับลูกค้าโรงพยาบาลและคลินิก',
      duration: '2 เดือน',
      servicesProvided: ['ออกแบบเว็บไซต์ (UX/UI)', 'พัฒนาเว็บไซต์', 'ระบบแคตตาล็อกสินค้า', 'ฟอร์มติดต่อสั่งซื้อแบบองค์กร (B2B)'],
      heroImage: '/images/case-studies/blue-bear/cover.png',
      challengeHeading: 'โจทย์ของโปรเจกต์',
      challenge: 'Blue Bear เป็นผู้ผลิตชุดยูนิฟอร์มทางการแพทย์คุณภาพสูงให้โรงพยาบาลและคลินิก แต่ยังไม่มีเว็บไซต์ที่แสดงสินค้าและรับคำสั่งซื้อจากลูกค้าองค์กรได้อย่างเป็นระบบ',
      solutionHeading: 'แนวทางที่เราทำ',
      solution: 'เราออกแบบเว็บไซต์ที่ดูน่าเชื่อถือและเป็นมืออาชีพ พร้อมระบบแคตตาล็อกสินค้าแยกตามประเภท และฟอร์มติดต่อสั่งซื้อสำหรับลูกค้าองค์กรโดยเฉพาะ',
      overviewHeading: 'ภาพรวมโปรเจกต์',
      overview: 'Blue Bear ต้องการเว็บไซต์ที่ช่วยให้โรงพยาบาลและคลินิกค้นหาสินค้า เปรียบเทียบตัวเลือก และติดต่อสั่งซื้อได้สะดวกขึ้น',
      approachHeading: 'กระบวนการทำงาน',
      approach: [
        { title: 'ทำความเข้าใจธุรกิจ', desc: 'เก็บข้อมูลไลน์สินค้า กลุ่มลูกค้า และขั้นตอนการสั่งซื้อแบบองค์กร' },
        { title: 'ออกแบบ UX/UI', desc: 'วางโครงสร้างแคตตาล็อกสินค้าให้ค้นหาและเปรียบเทียบได้ง่าย' },
        { title: 'พัฒนาและเชื่อมฟอร์มสั่งซื้อ', desc: 'พัฒนาเว็บไซต์พร้อมฟอร์มติดต่อสั่งซื้อสำหรับลูกค้าองค์กร' },
        { title: 'วางแผนคอนเทนต์สินค้า', desc: 'จัดระเบียบภาพและข้อมูลสินค้าให้ครบถ้วนน่าเชื่อถือ' },
      ],
      keyFeaturesHeading: 'ฟีเจอร์เด่น',
      keyFeatures: [
        { title: 'แคตตาล็อกสินค้าครบถ้วน', bullets: ['แยกหมวดหมู่สินค้าตามประเภทการใช้งาน', 'ภาพสินค้าความละเอียดสูงพร้อมรายละเอียดผ้าและขนาด', 'ค้นหาและกรองสินค้าได้สะดวก'] },
        { title: 'รองรับลูกค้าองค์กร (B2B)', bullets: ['ฟอร์มติดต่อสั่งซื้อสำหรับโรงพยาบาลและคลินิกโดยเฉพาะ', 'ระบบขอใบเสนอราคาสำหรับคำสั่งซื้อจำนวนมาก', 'ข้อมูลติดต่อฝ่ายขายที่เข้าถึงง่าย'] },
        { title: 'ความน่าเชื่อถือของแบรนด์', bullets: ['ดีไซน์ที่ดูเป็นมืออาชีพเหมาะกับลูกค้าองค์กร', 'หน้าแนะนำมาตรฐานคุณภาพและกระบวนการผลิต', 'โครงสร้างเว็บไซต์ที่เอื้อต่อการทำ SEO ในระยะยาว'] },
      ],
      backLabel: 'กลับไปหน้า Case Studies',
      servicesLabel: 'บริการที่ให้',
    },
    en: {
      badge: 'Apparel & Uniforms',
      client: 'Blue Bear',
      title: 'Blue Bear — Medical Uniform Manufacturer Website',
      desc: 'Designed and built a website for a medical uniform manufacturer, with a product catalog and a B2B order-inquiry flow to serve hospital and clinic customers.',
      duration: '2 months',
      servicesProvided: ['UX/UI Design', 'Web Development', 'Product Catalog System', 'B2B Order Inquiry Forms'],
      heroImage: '/images/case-studies/blue-bear/cover.png',
      challengeHeading: 'The Challenge',
      challenge: "Blue Bear manufactures high-quality medical uniforms for hospitals and clinics, but had no website to showcase its products or take orders from institutional customers in an organized way.",
      solutionHeading: 'Our Solution',
      solution: "We designed a trustworthy, professional-looking website with a product catalog organized by category, and a dedicated order-inquiry flow for institutional customers.",
      overviewHeading: 'Project Overview',
      overview: "Blue Bear needed a website that let hospitals and clinics browse products, compare options, and reach out to order more easily.",
      approachHeading: 'Our Approach',
      approach: [
        { title: 'Business Immersion', desc: "Gathered the product line, customer base, and institutional ordering process." },
        { title: 'UX/UI Design', desc: 'Structured the product catalog so it is easy to browse and compare.' },
        { title: 'Development & Order Form Integration', desc: 'Built the website with an order-inquiry flow for institutional customers.' },
        { title: 'Product Content Direction', desc: 'Organized product photography and specs to read as complete and trustworthy.' },
      ],
      keyFeaturesHeading: 'Key Features',
      keyFeatures: [
        { title: 'Complete Product Catalog', bullets: ['Products organized by category and use case', 'High-resolution photos with fabric and size details', 'Easy search and filtering'] },
        { title: 'Built for B2B Customers', bullets: ['Dedicated order-inquiry form for hospitals and clinics', 'Quote request flow for bulk orders', 'Easy-to-reach sales contact information'] },
        { title: 'Brand Credibility', bullets: ['Professional design suited to institutional buyers', 'A page on quality standards and manufacturing process', 'Site structure built with long-term SEO in mind'] },
      ],
      backLabel: 'Back to Case Studies',
      servicesLabel: 'Services Provided',
    },
  },
  {
    slug: 'thai-metal-aluminium',
    industryTag: 'Manufacturing',
    result: 'เว็บไซต์ใหม่',
    year: '2025',
    th: {
      badge: 'Manufacturing',
      client: 'Thai Metal Aluminium',
      title: 'เว็บไซต์โรงงานผลิตชิ้นส่วนอะลูมิเนียม Thai Metal Aluminium',
      desc: 'ออกแบบและพัฒนาเว็บไซต์องค์กรให้โรงงานผลิตชิ้นส่วนโลหะและอะลูมิเนียมความแม่นยำสูง เพื่อนำเสนอขีดความสามารถด้านการผลิตและมาตรฐานคุณภาพต่อลูกค้าอุตสาหกรรม',
      duration: '2 เดือน',
      servicesProvided: ['ออกแบบเว็บไซต์ (UX/UI)', 'พัฒนาเว็บไซต์', 'กำกับทิศทางคอนเทนต์เชิงเทคนิค', 'SEO สำหรับลูกค้าอุตสาหกรรม'],
      heroImage: '/images/case-studies/thai-metal-aluminium/cover.png',
      challengeHeading: 'โจทย์ของโปรเจกต์',
      challenge: 'Thai Metal Aluminium เป็นโรงงานผลิตชิ้นส่วนโลหะและอะลูมิเนียมความแม่นยำสูง แต่เว็บไซต์เดิมไม่สามารถสื่อสารขีดความสามารถด้านเครื่องจักรและมาตรฐานคุณภาพให้ลูกค้าอุตสาหกรรมเห็นภาพได้ชัดเจน',
      solutionHeading: 'แนวทางที่เราทำ',
      solution: 'เราออกแบบเว็บไซต์องค์กรที่ดูน่าเชื่อถือ นำเสนอกระบวนการผลิต เครื่องจักร และมาตรฐานคุณภาพอย่างเป็นระบบ พร้อมวางโครงสร้างคอนเทนต์ให้ค้นเจอง่ายบนการค้นหาของลูกค้าอุตสาหกรรม',
      overviewHeading: 'ภาพรวมโปรเจกต์',
      overview: 'Thai Metal Aluminium ต้องการเว็บไซต์ที่ช่วยสร้างความน่าเชื่อถือกับลูกค้าอุตสาหกรรมใหม่ และสื่อสารขีดความสามารถด้านการผลิตได้อย่างชัดเจน',
      approachHeading: 'กระบวนการทำงาน',
      approach: [
        { title: 'ทำความเข้าใจธุรกิจ', desc: 'เก็บข้อมูลกระบวนการผลิต เครื่องจักร และกลุ่มลูกค้าอุตสาหกรรมเป้าหมาย' },
        { title: 'ออกแบบ UX/UI', desc: 'วางโครงสร้างหน้าเว็บให้ขีดความสามารถและมาตรฐานคุณภาพเข้าถึงง่าย' },
        { title: 'พัฒนาเว็บไซต์องค์กร', desc: 'พัฒนาเว็บไซต์ที่โหลดเร็วและดูน่าเชื่อถือสำหรับลูกค้า B2B' },
        { title: 'วางแผน SEO เชิงเทคนิค', desc: 'วางโครงสร้างคอนเทนต์ให้ค้นเจอง่ายบนการค้นหาของลูกค้าอุตสาหกรรม' },
      ],
      keyFeaturesHeading: 'ฟีเจอร์เด่น',
      keyFeatures: [
        { title: 'นำเสนอขีดความสามารถการผลิต', bullets: ['แสดงเครื่องจักรและกระบวนการผลิตอย่างเป็นระบบ', 'ภาพถ่ายโรงงานและชิ้นงานความละเอียดสูง', 'หน้าแนะนำมาตรฐานคุณภาพและการรับรอง'] },
        { title: 'รองรับลูกค้าอุตสาหกรรม (B2B)', bullets: ['ฟอร์มติดต่อสอบถามสำหรับลูกค้าองค์กร', 'ข้อมูลติดต่อฝ่ายขายที่เข้าถึงง่าย', 'หน้าแสดงผลงานและลูกค้าอ้างอิง'] },
        { title: 'ความน่าเชื่อถือของแบรนด์', bullets: ['ดีไซน์ที่ดูเป็นมืออาชีพเหมาะกับลูกค้าอุตสาหกรรม', 'โครงสร้างคอนเทนต์เชิงเทคนิคที่เข้าใจง่าย', 'โครงสร้างเว็บไซต์ที่เอื้อต่อการทำ SEO ในระยะยาว'] },
      ],
      backLabel: 'กลับไปหน้า Case Studies',
      servicesLabel: 'บริการที่ให้',
    },
    en: {
      badge: 'Manufacturing',
      client: 'Thai Metal Aluminium',
      title: 'Thai Metal Aluminium — Precision Manufacturing Website',
      desc: 'Designed and built a corporate website for a precision metal and aluminium parts manufacturer, presenting its manufacturing capabilities and quality standards to industrial customers.',
      duration: '2 months',
      servicesProvided: ['UX/UI Design', 'Web Development', 'Technical Content Direction', 'SEO for Industrial Customers'],
      heroImage: '/images/case-studies/thai-metal-aluminium/cover.png',
      challengeHeading: 'The Challenge',
      challenge: "Thai Metal Aluminium manufactures precision metal and aluminium parts, but its old website couldn't clearly communicate its machining capabilities and quality standards to industrial customers.",
      solutionHeading: 'Our Solution',
      solution: "We designed a trustworthy corporate website that presents the manufacturing process, machinery, and quality standards systematically, with content structured to be found by industrial customers searching online.",
      overviewHeading: 'Project Overview',
      overview: "Thai Metal Aluminium needed a website that built credibility with new industrial customers and clearly communicated its manufacturing capabilities.",
      approachHeading: 'Our Approach',
      approach: [
        { title: 'Business Immersion', desc: "Gathered the manufacturing process, machinery, and target industrial customer base." },
        { title: 'UX/UI Design', desc: 'Structured the site so capabilities and quality standards are easy to reach.' },
        { title: 'Corporate Website Development', desc: 'Built a fast, trustworthy website for B2B customers.' },
        { title: 'Technical SEO Planning', desc: 'Structured content to be found by industrial customers searching online.' },
      ],
      keyFeaturesHeading: 'Key Features',
      keyFeatures: [
        { title: 'Showcasing Manufacturing Capability', bullets: ['Machinery and manufacturing process presented systematically', 'High-resolution photos of the factory and parts', 'A page on quality standards and certifications'] },
        { title: 'Built for Industrial B2B Customers', bullets: ['Inquiry form for institutional customers', 'Easy-to-reach sales contact information', 'A page showcasing past work and reference clients'] },
        { title: 'Brand Credibility', bullets: ['Professional design suited to industrial buyers', 'Technical content structured to be easy to understand', 'Site structure built with long-term SEO in mind'] },
      ],
      backLabel: 'Back to Case Studies',
      servicesLabel: 'Services Provided',
    },
  },
  {
    slug: 'vera',
    industryTag: 'E-Commerce',
    result: 'เว็บไซต์ใหม่',
    year: '2025',
    th: {
      badge: 'E-Commerce',
      client: 'VERA',
      title: 'เว็บไซต์อีคอมเมิร์ซแบรนด์กระเป๋า VERA',
      desc: 'ออกแบบและพัฒนาเว็บไซต์อีคอมเมิร์ซให้แบรนด์กระเป๋าที่ผลิตและขายออนไลน์ พร้อมระบบตะกร้าสินค้าและชำระเงิน เพื่อรองรับการขายตรงถึงลูกค้าทั่วประเทศ',
      duration: '3 เดือน',
      servicesProvided: ['ออกแบบเว็บไซต์ (UX/UI)', 'พัฒนาเว็บไซต์อีคอมเมิร์ซ', 'กำกับทิศทางภาพถ่ายสินค้า', 'ช่วยวางกลยุทธ์การตลาดดิจิทัล'],
      heroImage: '/images/case-studies/vera/cover.png',
      challengeHeading: 'โจทย์ของโปรเจกต์',
      challenge: 'VERA เป็นแบรนด์กระเป๋าที่ผลิตเองและเน้นขายผ่านช่องทางออนไลน์ ต้องการเว็บไซต์อีคอมเมิร์ซที่ดูพรีเมียมสมกับคุณภาพสินค้า พร้อมระบบตะกร้าสินค้าและชำระเงินที่ใช้งานง่าย เพื่อลดการขายผ่านมาร์เก็ตเพลสเพียงอย่างเดียว',
      solutionHeading: 'แนวทางที่เราทำ',
      solution: 'เราออกแบบเว็บไซต์อีคอมเมิร์ซโทนมินิมอลหรูหรา ให้ภาพถ่ายสินค้าเป็นจุดเด่น พร้อมระบบตะกร้าสินค้าและชำระเงินที่ครบวงจร และวางแนวทางคอนเทนต์ให้สอดคล้องกับภาพลักษณ์แบรนด์',
      overviewHeading: 'ภาพรวมโปรเจกต์',
      overview: 'VERA ต้องการเว็บไซต์ของแบรนด์เองเพื่อสร้างช่องทางขายตรงถึงลูกค้า ลดการพึ่งพามาร์เก็ตเพลส และสร้างความสัมพันธ์กับลูกค้าในระยะยาว',
      approachHeading: 'กระบวนการทำงาน',
      approach: [
        { title: 'ทำความเข้าใจแบรนด์', desc: 'เก็บข้อมูลไลน์สินค้า โทนภาพ และกลุ่มลูกค้าเป้าหมาย' },
        { title: 'ออกแบบ UX/UI', desc: 'วางโครงสร้างหน้าร้านออนไลน์ให้เลือกซื้อและเช็คเอาต์ได้ลื่นไหล' },
        { title: 'พัฒนาระบบอีคอมเมิร์ซ', desc: 'พัฒนาระบบตะกร้าสินค้า ชำระเงิน และจัดการคำสั่งซื้อ' },
        { title: 'วางแผนคอนเทนต์การตลาด', desc: 'วางแนวทางภาพถ่ายสินค้าและคอนเทนต์สำหรับโซเชียลมีเดีย' },
      ],
      keyFeaturesHeading: 'ฟีเจอร์เด่น',
      keyFeatures: [
        { title: 'ประสบการณ์แบรนด์บนเว็บไซต์', bullets: ['ดีไซน์มินิมอลหรูหราเข้ากับภาพลักษณ์แบรนด์', 'ภาพถ่ายสินค้าความละเอียดสูงหลายมุมมอง', 'หน้าคอลเลกชันสินค้าที่อัปเดตตามฤดูกาล'] },
        { title: 'ช้อปปิ้งและชำระเงินครบวงจร', bullets: ['ระบบตะกร้าสินค้าและเช็คเอาต์ในหน้าเดียว', 'รองรับช่องทางชำระเงินหลากหลาย', 'ระบบติดตามสถานะคำสั่งซื้อ'] },
        { title: 'สนับสนุนด้านการตลาด', bullets: ['วางแนวทางคอนเทนต์สำหรับโซเชียลมีเดีย', 'จัดระเบียบภาพถ่ายให้พร้อมใช้ในสื่อโฆษณา', 'โครงสร้างเว็บไซต์ที่เอื้อต่อการทำ SEO ในระยะยาว'] },
      ],
      backLabel: 'กลับไปหน้า Case Studies',
      servicesLabel: 'บริการที่ให้',
    },
    en: {
      badge: 'E-Commerce',
      client: 'VERA',
      title: 'VERA — Bag Brand E-Commerce Website',
      desc: 'Designed and built an e-commerce website for a self-manufactured bag brand selling online, with a cart and checkout flow to sell directly to customers nationwide.',
      duration: '3 months',
      servicesProvided: ['UX/UI Design', 'E-Commerce Development', 'Product Photography Direction', 'Digital Marketing Support'],
      heroImage: '/images/case-studies/vera/cover.png',
      challengeHeading: 'The Challenge',
      challenge: "VERA is a self-manufactured bag brand selling mainly online. It needed an e-commerce website premium enough to match its product quality, with an easy cart and checkout flow, to reduce reliance on marketplace-only selling.",
      solutionHeading: 'Our Solution',
      solution: "We designed a minimal, premium e-commerce website that lets product photography lead, with a complete cart and checkout flow, and a content direction matching the brand's image.",
      overviewHeading: 'Project Overview',
      overview: "VERA needed its own branded website to sell directly to customers, reduce marketplace dependency, and build long-term customer relationships.",
      approachHeading: 'Our Approach',
      approach: [
        { title: 'Brand Immersion', desc: "Gathered the product line, visual tone, and target audience." },
        { title: 'UX/UI Design', desc: 'Structured the storefront so browsing and checkout flow smoothly.' },
        { title: 'E-Commerce Development', desc: 'Built the cart, checkout, and order management system.' },
        { title: 'Marketing Content Direction', desc: 'Planned product photography and content direction for social channels.' },
      ],
      keyFeaturesHeading: 'Key Features',
      keyFeatures: [
        { title: 'Brand Experience Online', bullets: ['Minimal, premium design language matching the brand', 'High-resolution multi-angle product photography', 'A collections page updated by season'] },
        { title: 'Complete Shopping & Checkout', bullets: ['Single-page cart and checkout flow', 'Multiple payment methods supported', 'Order status tracking'] },
        { title: 'Marketing Support', bullets: ['Content direction for social media channels', 'Photography organized and ready for ad placements', 'Site structure built with long-term SEO in mind'] },
      ],
      backLabel: 'Back to Case Studies',
      servicesLabel: 'Services Provided',
    },
  },
  {
    slug: 'nfi',
    industryTag: 'Government & Public Sector',
    result: 'เว็บไซต์ใหม่',
    year: '2025',
    th: {
      badge: 'Government & Public Sector',
      client: 'NFI สถาบันอาหาร',
      title: 'เว็บไซต์สถาบันอาหาร กระทรวงอุตสาหกรรม',
      desc: 'ออกแบบและพัฒนาเว็บไซต์ให้สถาบันอาหาร หน่วยงานด้านวิจัยและทดสอบคุณภาพอาหารภายใต้กระทรวงอุตสาหกรรม เพื่อสื่อสารบริการห้องปฏิบัติการและงานวิจัยให้ผู้ประกอบการเข้าถึงได้ง่าย',
      duration: '3 เดือน',
      servicesProvided: ['ออกแบบเว็บไซต์ (UX/UI)', 'พัฒนาเว็บไซต์', 'ระบบค้นหาบริการห้องปฏิบัติการ', 'จัดระเบียบคอนเทนต์งานวิจัย'],
      heroImage: '/images/case-studies/nfi/cover.png',
      challengeHeading: 'โจทย์ของโปรเจกต์',
      challenge: 'สถาบันอาหารมีบริการห้องปฏิบัติการและงานวิจัยหลากหลายสาขา แต่เว็บไซต์เดิมเข้าถึงข้อมูลยาก ผู้ประกอบการไม่สามารถค้นหาบริการที่ต้องการได้สะดวก',
      solutionHeading: 'แนวทางที่เราทำ',
      solution: 'ออกแบบเว็บไซต์ใหม่ให้จัดหมวดหมู่บริการห้องปฏิบัติการและงานวิจัยอย่างเป็นระบบ พร้อมระบบค้นหาที่ช่วยให้ผู้ประกอบการพบบริการที่ต้องการได้รวดเร็ว',
      overviewHeading: 'ภาพรวมโปรเจกต์',
      overview: 'โปรเจกต์นี้มุ่งยกระดับการสื่อสารของหน่วยงานภาครัฐให้เข้าถึงง่ายและทันสมัย ตอบโจทย์ทั้งผู้ประกอบการและนักวิจัย',
      approachHeading: 'แนวทางที่เราทำ',
      approach: [
        { title: 'ทำความเข้าใจหน่วยงาน', desc: 'ลงพื้นที่เก็บข้อมูลโครงสร้างบริการ ห้องปฏิบัติการ และกลุ่มผู้ใช้งานหลัก' },
        { title: 'ออกแบบ UX/UI', desc: 'วางโครงสร้างหน้าเว็บให้บริการและงานวิจัยค้นหาและเข้าถึงได้ง่าย' },
        { title: 'พัฒนาเว็บไซต์', desc: 'พัฒนาเว็บไซต์ที่โหลดเร็วและรองรับการใช้งานจากผู้ประกอบการหลากหลายกลุ่ม' },
        { title: 'จัดระเบียบคอนเทนต์', desc: 'จัดระเบียบข้อมูลบริการและงานวิจัยให้ครบถ้วนและค้นหาง่าย' },
      ],
      keyFeaturesHeading: 'ฟีเจอร์เด่น',
      keyFeatures: [
        { title: 'บริการห้องปฏิบัติการครบถ้วน', bullets: ['แยกหมวดหมู่บริการตามประเภทการทดสอบ', 'ระบบค้นหาบริการที่ใช้งานง่าย', 'ข้อมูลขั้นตอนและระยะเวลาการให้บริการชัดเจน'] },
        { title: 'เข้าถึงงานวิจัยง่าย', bullets: ['คลังข้อมูลงานวิจัยที่ค้นหาได้สะดวก', 'จัดหมวดหมู่ตามสาขาการวิจัย', 'เอกสารดาวน์โหลดพร้อมใช้งาน'] },
        { title: 'ความน่าเชื่อถือของหน่วยงาน', bullets: ['ดีไซน์ที่สื่อถึงความเป็นหน่วยงานภาครัฐที่น่าเชื่อถือ', 'ข้อมูลติดต่อและช่องทางสอบถามที่เข้าถึงง่าย', 'โครงสร้างเว็บไซต์ที่เอื้อต่อการทำ SEO ในระยะยาว'] },
      ],
      backLabel: 'กลับไปหน้า Case Studies',
      servicesLabel: 'บริการที่ให้',
    },
    en: {
      badge: 'Government & Public Sector',
      client: 'NFI – National Food Institute',
      title: 'National Food Institute Website',
      desc: "Designed and built a website for the National Food Institute, a food research and testing body under Thailand's Ministry of Industry, to make its lab services and research easier for businesses to find and understand.",
      duration: '3 months',
      servicesProvided: ['UX/UI Design', 'Web Development', 'Lab Service Search System', 'Research Content Organization'],
      heroImage: '/images/case-studies/nfi/cover.png',
      challengeHeading: 'The Challenge',
      challenge: "The institute offers a wide range of lab and research services, but its old website made it hard for businesses to find the specific service they needed.",
      solutionHeading: 'Our Solution',
      solution: 'Redesigned the website to organize lab services and research into clear categories, with a search system that helps businesses find what they need quickly.',
      overviewHeading: 'Project Overview',
      overview: 'The project set out to modernize how a public institution communicates, making it accessible to both businesses and researchers.',
      approachHeading: 'Our Approach',
      approach: [
        { title: 'Institutional Immersion', desc: "Gathered the institute's service structure, lab capabilities, and core user groups." },
        { title: 'UX/UI Design', desc: 'Structured the site so services and research are easy to search and reach.' },
        { title: 'Web Development', desc: 'Built a fast website that serves a wide range of business users.' },
        { title: 'Content Organization', desc: 'Organized service and research content to be complete and easy to search.' },
      ],
      keyFeaturesHeading: 'Key Features',
      keyFeatures: [
        { title: 'Complete Lab Services', bullets: ['Services organized by testing category', 'Easy-to-use service search', 'Clear process and turnaround information'] },
        { title: 'Accessible Research', bullets: ['Searchable research archive', 'Organized by research field', 'Downloadable documents ready to use'] },
        { title: 'Institutional Credibility', bullets: ['Design that reads as a trustworthy public institution', 'Easy-to-reach contact and inquiry channels', 'Site structure built with long-term SEO in mind'] },
      ],
      backLabel: 'Back to Case Studies',
      servicesLabel: 'Services Provided',
    },
  },
  {
    slug: 'mbk',
    industryTag: 'Retail & Shopping Mall',
    result: 'แอปมือถือใหม่',
    year: '2025',
    th: {
      badge: 'Retail & Shopping Mall',
      client: 'MBK Center',
      title: 'แอปมือถือศูนย์การค้า MBK',
      desc: 'ออกแบบและพัฒนาแอปมือถือให้ศูนย์การค้า MBK Center เพื่อให้ลูกค้าค้นหาร้านค้า โปรโมชัน และสิทธิพิเศษได้สะดวกในที่เดียว',
      duration: '4 เดือน',
      servicesProvided: ['ออกแบบ UX/UI', 'พัฒนาแอปมือถือ', 'ระบบค้นหาร้านค้าและโปรโมชัน', 'ระบบสมาชิกและสิทธิพิเศษ'],
      heroImage: '/images/case-studies/mbk/cover.png',
      challengeHeading: 'โจทย์ของโปรเจกต์',
      challenge: 'ศูนย์การค้าขนาดใหญ่มีร้านค้าและโปรโมชันจำนวนมาก แต่ลูกค้าไม่มีช่องทางดิจิทัลที่รวบรวมข้อมูลเหล่านี้ไว้ในที่เดียวให้ค้นหาได้ง่าย',
      solutionHeading: 'แนวทางที่เราทำ',
      solution: 'พัฒนาแอปมือถือที่รวบรวมร้านค้า โปรโมชัน และผังศูนย์การค้าไว้ในที่เดียว พร้อมระบบสมาชิกมอบสิทธิพิเศษให้ลูกค้าประจำ',
      overviewHeading: 'ภาพรวมโปรเจกต์',
      overview: 'โปรเจกต์นี้ช่วยยกระดับประสบการณ์การช็อปปิ้งของลูกค้าศูนย์การค้าให้สะดวกและทันสมัยมากขึ้นผ่านช่องทางดิจิทัล',
      approachHeading: 'แนวทางที่เราทำ',
      approach: [
        { title: 'ทำความเข้าใจผู้ใช้งาน', desc: 'เก็บข้อมูลพฤติกรรมลูกค้าและโครงสร้างร้านค้าภายในศูนย์การค้า' },
        { title: 'ออกแบบ UX/UI', desc: 'วางโครงสร้างแอปให้ค้นหาร้านค้าและโปรโมชันเข้าถึงง่าย' },
        { title: 'พัฒนาแอปมือถือ', desc: 'พัฒนาแอปที่ใช้งานลื่นไหล รองรับผู้ใช้งานจำนวนมาก' },
        { title: 'เชื่อมระบบสมาชิก', desc: 'เชื่อมต่อระบบสมาชิกและสิทธิพิเศษเข้ากับแอป' },
      ],
      keyFeaturesHeading: 'ฟีเจอร์เด่น',
      keyFeatures: [
        { title: 'ค้นหาร้านค้าและโปรโมชันง่าย', bullets: ['ผังศูนย์การค้าแบบอินเทอร์แอกทีฟ', 'ค้นหาร้านค้าตามหมวดหมู่', 'รวบรวมโปรโมชันล่าสุดในที่เดียว'] },
        { title: 'สิทธิพิเศษสมาชิก', bullets: ['สะสมแต้มและแลกของรางวัล', 'แจ้งเตือนสิทธิพิเศษเฉพาะสมาชิก', 'ประวัติการใช้งานและสิทธิประโยชน์'] },
        { title: 'ประสบการณ์ใช้งานที่ลื่นไหล', bullets: ['ดีไซน์ทันสมัยใช้งานง่าย', 'รองรับผู้ใช้งานพร้อมกันจำนวนมาก', 'โครงสร้างระบบที่พร้อมต่อยอดในอนาคต'] },
      ],
      backLabel: 'กลับไปหน้า Case Studies',
      servicesLabel: 'บริการที่ให้',
    },
    en: {
      badge: 'Retail & Shopping Mall',
      client: 'MBK Center',
      title: 'MBK Center Mobile App',
      desc: 'Designed and built a mobile app for MBK Center, letting shoppers find stores, promotions, and member perks all in one place.',
      duration: '4 months',
      servicesProvided: ['UX/UI Design', 'Mobile App Development', 'Store & Promotion Search System', 'Membership & Rewards System'],
      heroImage: '/images/case-studies/mbk/cover.png',
      challengeHeading: 'The Challenge',
      challenge: "A large shopping mall has hundreds of stores and promotions, but shoppers had no digital channel bringing it all together in one searchable place.",
      solutionHeading: 'Our Solution',
      solution: 'Built a mobile app bringing stores, promotions, and the mall directory into one place, with a membership system offering perks to regular shoppers.',
      overviewHeading: 'Project Overview',
      overview: "The project modernized the mall's shopping experience through a digital channel built around what shoppers actually look for.",
      approachHeading: 'Our Approach',
      approach: [
        { title: 'User Immersion', desc: 'Gathered shopper behavior and the structure of stores across the mall.' },
        { title: 'UX/UI Design', desc: 'Structured the app so stores and promotions are easy to find.' },
        { title: 'Mobile App Development', desc: 'Built a smooth app that scales to a large number of users.' },
        { title: 'Membership Integration', desc: 'Connected a membership and rewards system to the app.' },
      ],
      keyFeaturesHeading: 'Key Features',
      keyFeatures: [
        { title: 'Easy Store & Promotion Search', bullets: ['Interactive mall directory', 'Search stores by category', 'Latest promotions gathered in one place'] },
        { title: 'Member Perks', bullets: ['Earn and redeem points', 'Member-only perk notifications', 'Usage history and benefits'] },
        { title: 'Smooth User Experience', bullets: ['Modern, easy-to-use design', 'Scales to a high volume of concurrent users', 'System structure built to extend in the future'] },
      ],
      backLabel: 'Back to Case Studies',
      servicesLabel: 'Services Provided',
    },
  },
  {
    slug: 'ditp',
    industryTag: 'Government & Public Sector',
    result: 'แอปมือถือใหม่',
    year: '2025',
    th: {
      badge: 'Government & Public Sector',
      client: 'DITP กรมส่งเสริมการค้าระหว่างประเทศ',
      title: 'แอปมือถือส่งเสริมผู้ประกอบการส่งออก DITP',
      desc: 'ออกแบบและพัฒนาแอปมือถือให้กรมส่งเสริมการค้าระหว่างประเทศ ต่อยอดจากแนวทางแอปที่เคยพัฒนาให้ก่อนหน้านี้ เพื่อสนับสนุนผู้ประกอบการไทยในการขยายตลาดส่งออก',
      duration: '4 เดือน',
      servicesProvided: ['ออกแบบ UX/UI', 'พัฒนาแอปมือถือ', 'ระบบข้อมูลตลาดส่งออก', 'เชื่อมต่อฐานข้อมูลผู้ประกอบการ'],
      heroImage: '/images/case-studies/ditp/cover.png',
      challengeHeading: 'โจทย์ของโปรเจกต์',
      challenge: 'กรมฯ ต้องการแอปมือถือเวอร์ชันใหม่ที่พัฒนาต่อยอดจากแนวทางเดิม ให้ทันสมัยและตอบโจทย์ผู้ประกอบการส่งออกไทยในยุคปัจจุบันมากขึ้น',
      solutionHeading: 'แนวทางที่เราทำ',
      solution: 'ศึกษาแนวทางแอปเดิมและพัฒนาต่อยอดด้วยเทคโนโลยีและดีไซน์ที่ทันสมัย พร้อมปรับปรุงการเข้าถึงข้อมูลตลาดส่งออกให้สะดวกขึ้น',
      overviewHeading: 'ภาพรวมโปรเจกต์',
      overview: 'โปรเจกต์นี้ช่วยยกระดับเครื่องมือดิจิทัลของภาครัฐให้สนับสนุนผู้ประกอบการส่งออกไทยได้อย่างมีประสิทธิภาพมากขึ้น',
      approachHeading: 'แนวทางที่เราทำ',
      approach: [
        { title: 'ศึกษาแนวทางเดิม', desc: 'ศึกษาโครงสร้างและฟีเจอร์ของแอปที่เคยพัฒนาไว้ก่อนหน้า เพื่อต่อยอดอย่างเหมาะสม' },
        { title: 'ออกแบบ UX/UI', desc: 'ออกแบบหน้าตาใหม่ให้ทันสมัยและใช้งานง่ายขึ้นสำหรับผู้ประกอบการ' },
        { title: 'พัฒนาแอปมือถือ', desc: 'พัฒนาแอปด้วยเทคโนโลยีปัจจุบัน รองรับการใช้งานที่เสถียร' },
        { title: 'เชื่อมฐานข้อมูล', desc: 'เชื่อมต่อฐานข้อมูลผู้ประกอบการและข้อมูลตลาดส่งออก' },
      ],
      keyFeaturesHeading: 'ฟีเจอร์เด่น',
      keyFeatures: [
        { title: 'ข้อมูลตลาดส่งออกครบถ้วน', bullets: ['ข้อมูลตลาดและโอกาสส่งออกอัปเดตสม่ำเสมอ', 'ค้นหาข้อมูลตามประเภทสินค้าและประเทศเป้าหมาย', 'แจ้งเตือนกิจกรรมและงานแสดงสินค้า'] },
        { title: 'สนับสนุนผู้ประกอบการ', bullets: ['ฐานข้อมูลผู้ประกอบการที่เชื่อมต่อกัน', 'ช่องทางติดต่อหน่วยงานที่เข้าถึงง่าย', 'คู่มือและเอกสารสำหรับผู้ส่งออก'] },
        { title: 'ประสบการณ์ใช้งานที่ทันสมัย', bullets: ['ดีไซน์ใหม่ใช้งานง่ายกว่าเดิม', 'ประสิทธิภาพการทำงานที่เสถียร', 'โครงสร้างระบบที่พร้อมต่อยอดในอนาคต'] },
      ],
      backLabel: 'กลับไปหน้า Case Studies',
      servicesLabel: 'บริการที่ให้',
    },
    en: {
      badge: 'Government & Public Sector',
      client: 'DITP – Department of International Trade Promotion',
      title: 'DITP Export Promotion Mobile App',
      desc: "Designed and built a mobile app for Thailand's Department of International Trade Promotion, building on an app we had developed for them previously, to help Thai exporters grow into new markets.",
      duration: '4 months',
      servicesProvided: ['UX/UI Design', 'Mobile App Development', 'Export Market Data System', 'Business Database Integration'],
      heroImage: '/images/case-studies/ditp/cover.png',
      challengeHeading: 'The Challenge',
      challenge: "The department wanted a new version of its mobile app, built on the earlier version's direction but modernized to better serve today's Thai exporters.",
      solutionHeading: 'Our Solution',
      solution: 'Reviewed the earlier app and rebuilt it with current technology and design, improving how exporters access market data.',
      overviewHeading: 'Project Overview',
      overview: 'The project modernized a public-sector digital tool to more effectively support Thai exporters.',
      approachHeading: 'Our Approach',
      approach: [
        { title: 'Reviewing the Earlier App', desc: 'Studied the structure and features of the app we had built previously to extend it appropriately.' },
        { title: 'UX/UI Design', desc: 'Designed a modern, easier-to-use interface for exporters.' },
        { title: 'Mobile App Development', desc: 'Built the app with current technology for stable performance.' },
        { title: 'Database Integration', desc: 'Connected the business database and export market data.' },
      ],
      keyFeaturesHeading: 'Key Features',
      keyFeatures: [
        { title: 'Complete Export Market Data', bullets: ['Regularly updated market and export opportunity data', 'Search by product category and target country', 'Notifications for trade events and fairs'] },
        { title: 'Support for Exporters', bullets: ['Connected business database', 'Easy-to-reach department contact channels', 'Guides and documents for exporters'] },
        { title: 'Modernized Experience', bullets: ['New design, easier to use than before', 'Stable performance', 'System structure built to extend in the future'] },
      ],
      backLabel: 'Back to Case Studies',
      servicesLabel: 'Services Provided',
    },
  },
  {
    slug: 'sra-bua',
    industryTag: 'F&B',
    result: 'เว็บไซต์ใหม่',
    year: '2025',
    th: {
      badge: 'F&B',
      client: 'Sra Bua by Kiin Kiin',
      title: 'เว็บไซต์ร้านอาหารไฟน์ไดนิ่ง Sra Bua by Kiin Kiin',
      desc: 'ออกแบบและพัฒนาเว็บไซต์ให้ร้านอาหารไฟน์ไดนิ่งสไตล์ไทยโมเดิร์น พร้อมระบบจองโต๊ะออนไลน์ เพื่อสื่อสารบรรยากาศหรูหราและความประณีตของอาหารให้ลูกค้าทั้งชาวไทยและต่างชาติ',
      duration: '3 เดือน',
      servicesProvided: ['ออกแบบ UX/UI', 'พัฒนาเว็บไซต์', 'ระบบจองโต๊ะออนไลน์', 'กำกับภาพถ่ายและคอนเทนต์'],
      heroImage: '/images/case-studies/sra-bua/cover.png',
      challengeHeading: 'โจทย์ของโปรเจกต์',
      challenge: 'ร้านอาหารไฟน์ไดนิ่งต้องการเว็บไซต์ที่สื่อสารความหรูหราและเอกลักษณ์ของอาหารไทยโมเดิร์นได้อย่างสมบูรณ์ พร้อมช่องทางจองโต๊ะที่สะดวกสำหรับลูกค้า',
      solutionHeading: 'แนวทางที่เราทำ',
      solution: 'ออกแบบเว็บไซต์ให้ภาพและบรรยากาศของร้านเป็นจุดเด่น พร้อมเชื่อมต่อระบบจองโต๊ะออนไลน์ให้ใช้งานง่ายทั้งภาษาไทยและอังกฤษ',
      overviewHeading: 'ภาพรวมโปรเจกต์',
      overview: 'โปรเจกต์นี้ช่วยยกระดับการสื่อสารแบรนด์ของร้านอาหารไฟน์ไดนิ่งให้ทันสมัยและเข้าถึงกลุ่มลูกค้าทั้งในและต่างประเทศได้ดีขึ้น',
      approachHeading: 'แนวทางที่เราทำ',
      approach: [
        { title: 'ทำความเข้าใจแบรนด์', desc: 'ลงพื้นที่เก็บข้อมูลบรรยากาศร้าน สไตล์อาหาร และตัวตนของเชฟ' },
        { title: 'ออกแบบ UX/UI', desc: 'วางโครงสร้างหน้าเว็บให้เมนูและการจองโต๊ะเข้าถึงง่าย เน้นภาพบรรยากาศหรูหรา' },
        { title: 'พัฒนาและเชื่อมระบบจอง', desc: 'พัฒนาเว็บไซต์สองภาษา เชื่อมต่อระบบจองโต๊ะออนไลน์' },
        { title: 'กำกับภาพถ่ายคอนเทนต์', desc: 'วางแนวทางภาพถ่ายอาหารและบรรยากาศร้านให้สื่อถึงความประณีต' },
      ],
      keyFeaturesHeading: 'ฟีเจอร์เด่น',
      keyFeatures: [
        { title: 'ประสบการณ์แบรนด์บนเว็บไซต์', bullets: ['ภาพบรรยากาศร้านและอาหารความละเอียดสูง', 'ดีไซน์หรูหราเข้ากับภาพลักษณ์ไฟน์ไดนิ่ง', 'เรื่องราวแนวคิดอาหารไทยโมเดิร์น'] },
        { title: 'การจองโต๊ะที่ใช้งานง่าย', bullets: ['ระบบจองโต๊ะออนไลน์เชื่อมต่อโดยตรงจากเว็บไซต์', 'รองรับสองภาษาสำหรับลูกค้าต่างชาติ', 'รองรับการใช้งานบนมือถือเต็มรูปแบบ'] },
        { title: 'ความน่าเชื่อถือของแบรนด์', bullets: ['ดีไซน์ที่สื่อถึงความเป็นร้านอาหารระดับพรีเมียม', 'หน้าแนะนำเชฟและแนวคิดอาหาร', 'โครงสร้างเว็บไซต์ที่เอื้อต่อการทำ SEO ในระยะยาว'] },
      ],
      backLabel: 'กลับไปหน้า Case Studies',
      servicesLabel: 'บริการที่ให้',
    },
    en: {
      badge: 'F&B',
      client: 'Sra Bua by Kiin Kiin',
      title: 'Sra Bua by Kiin Kiin — Fine-Dining Restaurant Website',
      desc: 'Designed and built a website for a modern Thai fine-dining restaurant, with an online table-reservation system, to carry the restaurant\'s refined atmosphere and cuisine to both Thai and international guests.',
      duration: '3 months',
      servicesProvided: ['UX/UI Design', 'Web Development', 'Online Reservation System', 'Photography & Content Direction'],
      heroImage: '/images/case-studies/sra-bua/cover.png',
      challengeHeading: 'The Challenge',
      challenge: 'The restaurant needed a website that fully captured its luxury atmosphere and modern Thai identity, with a reservation flow convenient for guests.',
      solutionHeading: 'Our Solution',
      solution: "Designed a website that puts the restaurant's imagery and atmosphere front and center, connected to an online table-reservation system in both Thai and English.",
      overviewHeading: 'Project Overview',
      overview: "The project modernized the restaurant's brand communication, reaching both local and international guests more effectively.",
      approachHeading: 'Our Approach',
      approach: [
        { title: 'Brand Immersion', desc: "Spent time understanding the restaurant's ambience, cuisine style, and the chef's story." },
        { title: 'UX/UI Design', desc: 'Structured the site so the menu and reservations are easy to reach, with the atmosphere front and center.' },
        { title: 'Development & Booking Integration', desc: 'Built a bilingual website connected to an online table-reservation flow.' },
        { title: 'Photography & Content Direction', desc: 'Directed photography of the food and ambience to read as refined and premium.' },
      ],
      keyFeaturesHeading: 'Key Features',
      keyFeatures: [
        { title: 'Brand Experience Online', bullets: ['High-resolution photography of the food and ambience', 'Luxury design language matching fine dining', "The story behind the restaurant's modern Thai concept"] },
        { title: 'Effortless Reservations', bullets: ['Online table reservation connected directly from the website', 'Bilingual for international guests', 'Fully responsive on mobile'] },
        { title: 'Brand Credibility', bullets: ['Design that reads as a premium dining destination', 'A page on the chef and culinary concept', 'Site structure built with long-term SEO in mind'] },
      ],
      backLabel: 'Back to Case Studies',
      servicesLabel: 'Services Provided',
    },
  },
]

export function getCaseStudy(slug: string) {
  return caseStudies.find((c) => c.slug === slug)
}
