import type { Metadata } from 'next'
import LegalPage, { type LegalSection } from '@/components/LegalPage'
import { type Lang } from '@/lib/i18n'
import { alt } from '@/lib/seo'

export async function generateStaticParams() {
  return [{ lang: 'th' }, { lang: 'en' }]
}

export async function generateMetadata({ params }: { params: { lang: Lang } }): Promise<Metadata> {
  const isEN = params.lang === 'en'
  const title = isEN ? 'Terms of Service | Haliviq' : 'ข้อกำหนดการให้บริการ | Haliviq'
  const description = isEN
    ? "The terms and conditions that govern your use of Haliviq's website and services."
    : 'ข้อกำหนดและเงื่อนไขการใช้งานเว็บไซต์และบริการของ Haliviq'
  const siteUrl = `https://haliviq.com/${params.lang}/terms`
  return { title, description, alternates: alt(siteUrl), openGraph: { title, description, url: siteUrl } }
}

const en: LegalSection[] = [
  { title: '1. Acceptance of Terms', body: 'By accessing or using the Haliviq website, or by engaging Haliviq Co., Ltd. for any service, you agree to be bound by these Terms of Service. If you do not agree with any part of these terms, please do not use our website or services.', note: 'If you are accepting on behalf of a company or organisation, you confirm that you have authority to bind it.' },
  { title: '2. Definitions', items: ['"Haliviq", "we", "us" means Haliviq Co., Ltd., a company registered in Thailand.', '"Client" or "you" means the person or organisation that visits our website or engages us for services.', '"Services" means strategy, UX/UI design, website and application development, AI solutions, maintenance and related work.', '"Deliverables" means the designs, code, documents and other materials we create specifically for a Client under a signed proposal or contract.', '"Agreement" means the written proposal, statement of work or contract agreed for an engagement, together with these terms.'] },
  { title: '3. Our Services', body: 'Haliviq provides digital product strategy, UX/UI design, website and application development, and AI solutions. The scope, timeline, deliverables and fees of each engagement are defined in the Agreement, which takes precedence over these general terms for that engagement if the two conflict.' },
  { title: '4. Use of This Website', body: 'You may use our website for lawful purposes only. You agree not to:', items: ['attempt to gain unauthorised access to our systems, servers or data;', 'introduce malware, scrape the site at a rate that harms performance, or interfere with its operation;', 'use the site to send spam, unlawful, misleading or infringing material;', 'impersonate any person or misrepresent your affiliation with any person or organisation.'], note: 'We may suspend or restrict access to the website at any time without notice for maintenance, security or legal reasons.' },
  { title: '5. Enquiries and Form Submissions', body: 'Information you send through our contact form, email, LINE or WhatsApp is used to respond to your enquiry and prepare proposals, as described in our Privacy Policy. Submitting an enquiry does not create a contract; an engagement begins only when both parties sign or expressly accept a written Agreement.' },
  { title: '6. Proposals, Estimates and Change Requests', items: ['Proposals and estimates are valid for 30 days unless stated otherwise.', 'Work outside the agreed scope is handled as a change request, with any impact on fees and timeline agreed in writing before the work begins.', 'Timelines depend on timely Client feedback, content and access; delays on the Client side may move delivery dates accordingly.', 'Each engagement includes the number of review rounds stated in the Agreement; additional rounds may be charged.'] },
  { title: '7. Client Responsibilities', body: 'Clients are responsible for providing timely feedback, necessary access and accurate information, and for ensuring that content, images, fonts, data and trademarks they supply are lawful and that they hold the rights to use them. Delays or scope changes caused by the Client may affect timelines and may incur additional fees as outlined in the relevant Agreement.' },
  { title: '8. Payment Terms', items: ['Fees, payment schedules and milestones are set out in each Agreement.', 'Unless otherwise agreed, invoices are due within 15 days of issue.', 'Fees are exclusive of value-added tax (VAT) and withholding tax unless stated otherwise.', 'Overdue amounts may incur interest at the maximum rate permitted by Thai law.', 'Haliviq may pause work on overdue accounts, and withhold delivery or transfer of Deliverables, until payment is received.'] },
  { title: '9. Acceptance and Warranty Period', body: 'Deliverables are considered accepted when the Client approves them in writing, or if no written feedback is received within 7 business days of delivery. Unless the Agreement states otherwise, we will fix defects that do not conform to the agreed specification, reported within 30 days of acceptance, at no additional charge. Ongoing maintenance, hosting and new features are provided only under a separate maintenance or change agreement.' },
  { title: '10. Intellectual Property', body: 'Unless otherwise agreed in a signed contract, ownership of custom code, designs and other Deliverables created specifically for a Client transfers to that Client upon full payment.', items: ['Haliviq retains ownership of its pre-existing tools, frameworks, libraries, templates and general know-how, and grants the Client a non-exclusive, perpetual licence to use them as part of the Deliverables.', 'Haliviq may reuse non-confidential, non-client-specific components in future projects.', 'Until full payment is received, the Client holds only a limited licence to use the Deliverables.'] },
  { title: '11. Third-Party Tools and Open-Source Software', body: 'Our work may incorporate third-party services, libraries, fonts, stock assets, cloud platforms and open-source software. These remain subject to their own licences and terms, which the Client agrees to comply with. Fees charged by third parties (for example hosting, domains, paid plug-ins, API usage and licences) are the Client\'s responsibility unless the Agreement states otherwise.' },
  { title: '12. AI-Assisted Work and AI Solutions', body: 'We may use AI tools to assist with research, design, code and content, always under human review. For AI solutions we build for you:', items: ['AI outputs can be inaccurate, incomplete or biased and should be reviewed by a qualified person before being relied on for important decisions.', 'The Client is responsible for the lawful use of AI features, including the data they provide to the system and how outputs are used.', 'We do not use Client confidential data to train public AI models without the Client\'s written consent.', 'Model providers\' terms and usage policies apply to the AI services integrated into the solution.'] },
  { title: '13. Confidentiality', body: 'Both parties agree to keep confidential any non-public business, technical or financial information disclosed during an engagement, and to use it only for the purposes of that engagement. This obligation does not apply to information that is public through no fault of the recipient, already known to it, independently developed, or required to be disclosed by law. A separate Non-Disclosure Agreement (NDA) is available on request before any sensitive information is shared.' },
  { title: '14. Portfolio and Publicity', body: 'Unless the Client objects in writing or the Agreement says otherwise, Haliviq may display the project name, the Client\'s name and logo, and non-confidential screenshots or descriptions of the Deliverables in our portfolio, case studies and marketing materials. We will not disclose confidential information or credentials.' },
  { title: '15. Personal Data', body: 'Each party will comply with applicable data protection laws, including Thailand\'s Personal Data Protection Act B.E. 2562 (2019). Where we process personal data on a Client\'s behalf, we will do so only on the Client\'s documented instructions and under a data processing agreement where required. See our Privacy Policy for how we handle data collected through our own website and business dealings.' },
  { title: '16. Warranties and Disclaimer', body: 'We provide our Services with reasonable skill and care in line with industry standards. Except as expressly stated in the Agreement, and to the extent permitted by law, the website and Services are provided "as is" without warranties of any kind, including fitness for a particular purpose, uninterrupted or error-free operation, or specific business results such as traffic, rankings or revenue.' },
  { title: '17. Limitation of Liability', body: 'To the maximum extent permitted by law, Haliviq\'s total liability arising from any engagement is limited to the fees paid for the specific Service giving rise to the claim, and we are not liable for indirect, incidental, special or consequential damages, loss of profit, loss of data or loss of goodwill. Nothing in these terms limits liability that cannot be limited by law, such as for fraud or wilful misconduct.' },
  { title: '18. Indemnification', body: 'The Client agrees to indemnify Haliviq against third-party claims, losses and reasonable costs arising from content, data or materials the Client supplies, or from the Client\'s use of the Deliverables in breach of law or these terms. Haliviq will likewise indemnify the Client against third-party claims that Deliverables created solely by Haliviq infringe that party\'s intellectual property rights, provided the Client notifies us promptly and allows us to control the defence.' },
  { title: '19. Termination', body: 'Either party may terminate an active engagement in accordance with the notice period in the Agreement, or immediately if the other party materially breaches it and fails to remedy the breach within 14 days of written notice. On termination, the Client pays for work completed and non-cancellable costs incurred up to the termination date, and we will deliver work in progress once all amounts due are paid. Sections that by their nature should survive (intellectual property, confidentiality, payment, liability, governing law) continue after termination.' },
  { title: '20. Force Majeure', body: 'Neither party is liable for delay or failure to perform caused by events beyond its reasonable control, including natural disasters, epidemics, war, civil unrest, government action, power or internet outages, or failures of third-party platforms. The affected party will notify the other promptly and resume performance as soon as reasonably possible.' },
  { title: '21. Governing Law and Dispute Resolution', body: 'These Terms are governed by the laws of the Kingdom of Thailand. The parties will first try in good faith to resolve any dispute through discussion between senior representatives for at least 30 days. If unresolved, the dispute is subject to the exclusive jurisdiction of the courts of Thailand, unless a specific Agreement provides otherwise.' },
  { title: '22. General', items: ['Entire agreement: these terms and the Agreement are the entire understanding between the parties for the engagement and replace earlier discussions.', 'Severability: if any provision is found unenforceable, the rest remains in effect.', 'No waiver: failure to enforce a right is not a waiver of it.', 'Assignment: the Client may not assign the Agreement without our written consent; Haliviq may use subcontractors and remains responsible for their work.', 'Notices: formal notices must be in writing and sent to the email or postal address stated in the Agreement or in the Contact section below.', 'Language: these terms are provided in Thai and English; if the two differ, the Thai version prevails.'] },
  { title: '23. Changes to These Terms', body: 'We may update these Terms of Service from time to time. Material changes will be reflected by an updated "last updated" date on this page. Continued use of our website or services after changes take effect constitutes acceptance of the revised terms. Changes do not alter the terms of an Agreement already signed.' },
  { title: '24. Contact Us', body: 'If you have questions about these Terms of Service, please contact us at info@haliviq.com or write to Haliviq Co., Ltd., 111 Sukhumvit Rd, Bang Chak, Phra Khanong, Bangkok 10260, Thailand.' },
]

const th: LegalSection[] = [
  { title: '1. การยอมรับข้อกำหนด', body: 'เมื่อท่านใช้เว็บไซต์ของ Haliviq หรือว่าจ้างบริษัท ฮาลิวิค จำกัด ให้ทำงานใด ๆ ถือว่าท่านยอมรับข้อกำหนดการให้บริการฉบับนี้ หากไม่ยอมรับข้อใดข้อหนึ่ง โปรดอย่าใช้เว็บไซต์หรือบริการของเรา', note: 'หากท่านยอมรับในนามบริษัทหรือองค์กร ท่านยืนยันว่ามีอำนาจทำให้องค์กรนั้นผูกพันตามข้อกำหนดนี้' },
  { title: '2. คำนิยาม', items: ['"Haliviq" "เรา" หมายถึง บริษัท ฮาลิวิค จำกัด ซึ่งจดทะเบียนในประเทศไทย', '"ลูกค้า" หรือ "ท่าน" หมายถึง บุคคลหรือองค์กรที่เข้าชมเว็บไซต์หรือว่าจ้างเรา', '"บริการ" หมายถึง การวางกลยุทธ์ ออกแบบ UX/UI พัฒนาเว็บไซต์และแอปพลิเคชัน ทำระบบ AI ดูแลรักษา และงานที่เกี่ยวข้อง', '"งานส่งมอบ" หมายถึง ดีไซน์ Code เอกสาร และสิ่งอื่นที่เราสร้างเฉพาะให้ลูกค้าตามข้อเสนอหรือสัญญาที่ลงนาม', '"สัญญา" หมายถึง ข้อเสนอ ขอบเขตงาน (SOW) หรือสัญญาเป็นลายลักษณ์อักษรของแต่ละโปรเจกต์ รวมกับข้อกำหนดฉบับนี้'] },
  { title: '3. บริการของเรา', body: 'Haliviq ให้บริการวางกลยุทธ์ผลิตภัณฑ์ดิจิทัล ออกแบบ UX/UI พัฒนาเว็บไซต์และแอปพลิเคชัน และทำระบบ AI ขอบเขตงาน ระยะเวลา งานที่ส่งมอบ และค่าบริการของแต่ละโปรเจกต์กำหนดไว้ในสัญญา หากขัดกับข้อกำหนดทั่วไปนี้ ให้ถือตามสัญญาสำหรับโปรเจกต์นั้น' },
  { title: '4. การใช้งานเว็บไซต์', body: 'ท่านใช้เว็บไซต์ของเราได้เฉพาะเพื่อวัตถุประสงค์ที่ชอบด้วยกฎหมาย และตกลงว่าจะไม่:', items: ['พยายามเข้าระบบ เซิร์ฟเวอร์ หรือข้อมูลของเราโดยไม่ได้รับอนุญาต', 'ใส่มัลแวร์ ดึงข้อมูลจากเว็บไซต์มากจนกระทบการทำงาน หรือรบกวนการทำงานของเว็บไซต์', 'ใช้เว็บไซต์ส่งสแปม หรือเนื้อหาที่ผิดกฎหมาย หลอกลวง หรือละเมิดสิทธิ์', 'แอบอ้างเป็นคนอื่น หรืออ้างความสัมพันธ์กับบุคคลหรือองค์กรอื่นอย่างเท็จ'], note: 'เราอาจระงับหรือจำกัดการเข้าเว็บไซต์ได้ทุกเมื่อโดยไม่ต้องแจ้งล่วงหน้า เพื่อการบำรุงรักษา ความปลอดภัย หรือเหตุผลทางกฎหมาย' },
  { title: '5. การสอบถามและส่งแบบฟอร์ม', body: 'ข้อมูลที่ท่านส่งผ่านแบบฟอร์มติดต่อ อีเมล LINE หรือ WhatsApp จะใช้เพื่อตอบกลับและจัดทำข้อเสนอ ตามที่ระบุในนโยบายความเป็นส่วนตัว การส่งข้อสอบถามไม่ถือเป็นการทำสัญญา การว่าจ้างจะเริ่มก็ต่อเมื่อทั้งสองฝ่ายลงนามหรือยอมรับสัญญาเป็นลายลักษณ์อักษรอย่างชัดเจนเท่านั้น' },
  { title: '6. ข้อเสนอ ใบประเมินราคา และคำขอเปลี่ยนแปลง', items: ['ข้อเสนอและใบประเมินราคามีผล 30 วัน เว้นแต่ระบุไว้เป็นอย่างอื่น', 'งานนอกขอบเขตที่ตกลงให้ทำจะถือเป็นคำขอเปลี่ยนแปลง (Change Request) โดยต้องตกลงเป็นลายลักษณ์อักษรก่อนเริ่มงานว่าค่าบริการและระยะเวลาจะเปลี่ยนไปอย่างไร', 'ระยะเวลาขึ้นอยู่กับว่าลูกค้าให้ความเห็น เนื้อหา และสิทธิ์เข้าถึงได้ทันเวลาหรือไม่ หากฝั่งลูกค้าล่าช้า กำหนดส่งมอบอาจเลื่อนออกไป', 'แต่ละโปรเจกต์มีจำนวนรอบแก้ไขตามที่ระบุในสัญญา การแก้ไขเพิ่มอาจมีค่าใช้จ่าย'] },
  { title: '7. ความรับผิดชอบของลูกค้า', body: 'ลูกค้ามีหน้าที่ให้ความเห็น สิทธิ์เข้าถึง และข้อมูลที่ถูกต้องให้ทันเวลา และรับรองว่าเนื้อหา รูปภาพ ฟอนต์ ข้อมูล และเครื่องหมายการค้าที่ลูกค้าให้เรานั้นถูกกฎหมายและลูกค้ามีสิทธิ์ใช้ หากลูกค้าล่าช้าหรือเปลี่ยนขอบเขตงาน อาจกระทบกำหนดเวลา และอาจมีค่าใช้จ่ายเพิ่มตามที่ระบุในสัญญา' },
  { title: '8. เงื่อนไขการชำระเงิน', items: ['ค่าบริการ กำหนดชำระเงิน และงวดงาน (Milestone) ระบุไว้ในสัญญาของแต่ละโปรเจกต์', 'เว้นแต่ตกลงเป็นอย่างอื่น ใบแจ้งหนี้ต้องชำระภายใน 15 วันนับจากวันที่ออก', 'ค่าบริการยังไม่รวมภาษีมูลค่าเพิ่ม (VAT) และภาษีหัก ณ ที่จ่าย เว้นแต่ระบุไว้เป็นอย่างอื่น', 'ยอดที่ค้างชำระอาจมีดอกเบี้ยในอัตราสูงสุดตามที่กฎหมายไทยอนุญาต', 'หากมียอดค้างชำระ Haliviq อาจหยุดงานชั่วคราว และชะลอการส่งมอบหรือโอนงานส่งมอบ จนกว่าจะได้รับเงิน'] },
  { title: '9. การตรวจรับงานและระยะรับประกัน', body: 'งานส่งมอบถือว่าตรวจรับแล้วเมื่อลูกค้าอนุมัติเป็นลายลักษณ์อักษร หรือเมื่อไม่ได้รับความเห็นเป็นลายลักษณ์อักษรภายใน 7 วันทำการนับจากวันส่งมอบ เว้นแต่สัญญาระบุเป็นอย่างอื่น หากพบข้อบกพร่องที่ไม่ตรงตามข้อกำหนดที่ตกลงกันและแจ้งภายใน 30 วันนับจากตรวจรับ เราจะแก้ไขให้โดยไม่คิดค่าใช้จ่ายเพิ่ม ส่วนการบำรุงรักษา โฮสติ้ง และฟีเจอร์ใหม่ จะทำภายใต้สัญญาบำรุงรักษาหรือสัญญาเปลี่ยนแปลงแยกต่างหากเท่านั้น' },
  { title: '10. ทรัพย์สินทางปัญญา', body: 'เว้นแต่ตกลงเป็นอย่างอื่นในสัญญาที่ลงนามร่วมกัน กรรมสิทธิ์ใน Code ดีไซน์ และงานส่งมอบอื่นที่สร้างเฉพาะให้ลูกค้า จะโอนเป็นของลูกค้าเมื่อชำระเงินครบ', items: ['Haliviq ยังเป็นเจ้าของเครื่องมือ Framework ไลบรารี เทมเพลต และความรู้ทั่วไปที่มีอยู่ก่อน และให้ลูกค้าใช้สิ่งเหล่านี้ในฐานะส่วนหนึ่งของงานส่งมอบได้แบบไม่เฉพาะเจาะจงและไม่มีกำหนดเวลา', 'Haliviq นำส่วนประกอบที่ไม่เป็นความลับและไม่เฉพาะกับลูกค้ารายนั้นไปใช้ในโปรเจกต์อื่นได้', 'จนกว่าจะชำระเงินครบ ลูกค้ามีสิทธิ์ใช้งานงานส่งมอบอย่างจำกัดเท่านั้น'] },
  { title: '11. เครื่องมือของบุคคลที่สามและโอเพนซอร์ส', body: 'งานของเราอาจใช้บริการ ไลบรารี ฟอนต์ ภาพสต็อก แพลตฟอร์ม Cloud และซอฟต์แวร์โอเพนซอร์สของบุคคลที่สาม ซึ่งมีใบอนุญาตและข้อกำหนดของตนเอง และลูกค้าตกลงทำตามข้อกำหนดเหล่านั้น ค่าใช้จ่ายของบุคคลที่สาม (เช่น โฮสติ้ง โดเมน ปลั๊กอินแบบเสียเงิน การใช้ API และลิขสิทธิ์) ลูกค้าเป็นผู้รับผิดชอบ เว้นแต่สัญญาระบุเป็นอย่างอื่น' },
  { title: '12. งานที่ใช้ AI ช่วยและโซลูชัน AI', body: 'เราอาจใช้เครื่องมือ AI ช่วยงานค้นคว้า ดีไซน์ Code และเนื้อหา โดยมีคนตรวจเสมอ สำหรับระบบ AI ที่เราพัฒนาให้ท่าน:', items: ['ผลลัพธ์จาก AI อาจไม่ถูกต้อง ไม่ครบ หรือมีอคติ ควรให้ผู้เชี่ยวชาญตรวจก่อนนำไปใช้ตัดสินใจเรื่องสำคัญ', 'ลูกค้ามีหน้าที่ใช้ฟีเจอร์ AI อย่างถูกกฎหมาย ทั้งข้อมูลที่ป้อนเข้าระบบและการนำผลลัพธ์ไปใช้', 'เราไม่ใช้ข้อมูลลับของลูกค้าฝึกโมเดล AI สาธารณะ หากไม่ได้รับความยินยอมเป็นลายลักษณ์อักษร', 'ข้อกำหนดและนโยบายการใช้งานของผู้ให้บริการโมเดลมีผลกับบริการ AI ที่รวมอยู่ในระบบ'] },
  { title: '13. การรักษาความลับ', body: 'ทั้งสองฝ่ายตกลงรักษาความลับของข้อมูลทางธุรกิจ เทคนิค หรือการเงินที่ไม่เปิดเผยต่อสาธารณะ ซึ่งแลกเปลี่ยนกันระหว่างทำงานร่วมกัน และใช้เพื่อโปรเจกต์นั้นเท่านั้น หน้าที่นี้ไม่ครอบคลุมข้อมูลที่เป็นสาธารณะโดยผู้รับไม่ได้เป็นต้นเหตุ ข้อมูลที่ผู้รับรู้อยู่แล้ว ที่ผู้รับพัฒนาขึ้นเอง หรือที่กฎหมายกำหนดให้เปิดเผย ก่อนแบ่งปันข้อมูลที่อ่อนไหว สามารถขอทำข้อตกลงไม่เปิดเผยข้อมูล (NDA) แยกต่างหากได้' },
  { title: '14. ผลงานและการเผยแพร่', body: 'เว้นแต่ลูกค้าคัดค้านเป็นลายลักษณ์อักษรหรือสัญญาระบุเป็นอย่างอื่น Haliviq แสดงชื่อโปรเจกต์ ชื่อและโลโก้ลูกค้า และภาพหน้าจอหรือคำอธิบายงานส่งมอบที่ไม่เป็นความลับ ในผลงาน กรณีศึกษา และสื่อการตลาดของเราได้ โดยจะไม่เปิดเผยข้อมูลลับหรือรหัสผ่านใด ๆ' },
  { title: '15. ข้อมูลส่วนบุคคล', body: 'แต่ละฝ่ายจะปฏิบัติตามกฎหมายคุ้มครองข้อมูลส่วนบุคคลที่เกี่ยวข้อง รวมถึงพระราชบัญญัติคุ้มครองข้อมูลส่วนบุคคล พ.ศ. 2562 (PDPA) หากเราประมวลผลข้อมูลส่วนบุคคลในนามลูกค้า เราจะทำตามคำสั่งที่เป็นลายลักษณ์อักษรของลูกค้าเท่านั้น และภายใต้ข้อตกลงประมวลผลข้อมูลเมื่อกฎหมายกำหนด ดูวิธีจัดการข้อมูลที่เก็บผ่านเว็บไซต์และการติดต่อทางธุรกิจได้ที่นโยบายความเป็นส่วนตัว' },
  { title: '16. การรับประกันและข้อสงวนสิทธิ์', body: 'เราให้บริการด้วยความชำนาญและความระมัดระวังตามมาตรฐานอุตสาหกรรม เว้นแต่ที่ระบุชัดเจนในสัญญา และภายใต้ขอบเขตที่กฎหมายอนุญาต เว็บไซต์และบริการให้ "ตามสภาพ" โดยไม่มีการรับประกันใด ๆ ทั้งความเหมาะสมกับวัตถุประสงค์เฉพาะ การทำงานที่ไม่สะดุดหรือไม่มีข้อผิดพลาด หรือผลลัพธ์ทางธุรกิจเฉพาะ เช่น ยอดผู้เข้าชม อันดับ หรือรายได้' },
  { title: '17. ข้อจำกัดความรับผิด', body: 'ภายใต้ขอบเขตสูงสุดที่กฎหมายอนุญาต ความรับผิดรวมของ Haliviq ที่เกิดจากงานใด ๆ จำกัดอยู่ที่ค่าบริการที่ได้รับชำระสำหรับบริการที่เกี่ยวข้องกับข้อเรียกร้องนั้น และเราจะไม่รับผิดต่อความเสียหายทางอ้อม โดยบังเอิญ เป็นพิเศษ หรือที่เป็นผลสืบเนื่อง การสูญเสียกำไร ข้อมูล หรือชื่อเสียง ข้อกำหนดนี้ไม่จำกัดความรับผิดที่กฎหมายไม่อนุญาตให้จำกัด เช่น กรณีฉ้อโกงหรือจงใจทำผิด' },
  { title: '18. การชดใช้ค่าเสียหาย', body: 'ลูกค้าตกลงชดใช้ให้ Haliviq สำหรับข้อเรียกร้อง ความเสียหาย และค่าใช้จ่ายอันสมควรจากบุคคลที่สาม ที่เกิดจากเนื้อหา ข้อมูล หรือวัสดุที่ลูกค้าจัดหา หรือจากการที่ลูกค้าใช้งานส่งมอบฝ่าฝืนกฎหมายหรือข้อกำหนดนี้ ในทำนองเดียวกัน Haliviq จะชดใช้ให้ลูกค้าสำหรับข้อเรียกร้องจากบุคคลที่สามว่างานส่งมอบที่ Haliviq สร้างขึ้นเองฝ่ายเดียวละเมิดทรัพย์สินทางปัญญา โดยลูกค้าต้องแจ้งเราโดยเร็วและให้เราเป็นผู้ดูแลการต่อสู้คดี' },
  { title: '19. การยกเลิกสัญญา', body: 'คู่สัญญาฝ่ายใดฝ่ายหนึ่งยกเลิกโปรเจกต์ที่กำลังทำอยู่ได้ โดยแจ้งล่วงหน้าตามระยะเวลาในสัญญา หรือยกเลิกทันทีหากอีกฝ่ายผิดสัญญาอย่างร้ายแรงและไม่แก้ไขภายใน 14 วันนับจากได้รับหนังสือแจ้ง เมื่อยกเลิก ลูกค้าต้องชำระค่างานที่ทำเสร็จและค่าใช้จ่ายที่ยกเลิกไม่ได้จนถึงวันที่ยกเลิก และเราจะส่งมอบงานที่ทำค้างอยู่เมื่อได้รับชำระครบ ข้อกำหนดที่โดยสภาพต้องมีผลต่อไป (ทรัพย์สินทางปัญญา การรักษาความลับ การชำระเงิน ความรับผิด กฎหมายที่ใช้บังคับ) ยังมีผลหลังยกเลิก' },
  { title: '20. เหตุสุดวิสัย', body: 'ทั้งสองฝ่ายไม่ต้องรับผิดต่อความล่าช้าหรือการไม่ปฏิบัติตามสัญญาที่เกิดจากเหตุที่เกินกว่าจะควบคุมได้ตามสมควร เช่น ภัยธรรมชาติ โรคระบาด สงคราม ความไม่สงบ การกระทำของรัฐ ไฟฟ้าหรืออินเทอร์เน็ตขัดข้อง หรือแพลตฟอร์มของบุคคลที่สามล่ม ฝ่ายที่ได้รับผลกระทบจะแจ้งอีกฝ่ายโดยเร็ว และกลับมาทำงานต่อทันทีเมื่อทำได้' },
  { title: '21. กฎหมายที่ใช้บังคับและการระงับข้อพิพาท', body: 'ข้อกำหนดนี้อยู่ภายใต้กฎหมายแห่งราชอาณาจักรไทย คู่สัญญาจะพยายามระงับข้อพิพาทโดยสุจริตผ่านการเจรจาระหว่างผู้แทนระดับอาวุโสไม่น้อยกว่า 30 วันก่อน หากไม่สำเร็จ ข้อพิพาทอยู่ในเขตอำนาจศาลไทยแต่เพียงผู้เดียว เว้นแต่สัญญาเฉพาะกำหนดเป็นอย่างอื่น' },
  { title: '22. ข้อกำหนดทั่วไป', items: ['ข้อตกลงทั้งหมด: ข้อกำหนดนี้และสัญญาเป็นข้อตกลงทั้งหมดระหว่างคู่สัญญาสำหรับโปรเจกต์ และแทนที่สิ่งที่คุยกันก่อนหน้า', 'ข้อที่บังคับใช้ไม่ได้: หากข้อใดบังคับใช้ไม่ได้ ข้อที่เหลือยังมีผลต่อไป', 'การไม่ใช้สิทธิ์: การไม่ใช้สิทธิ์ครั้งใดไม่ถือว่าสละสิทธิ์นั้น', 'การโอนสิทธิ์: ลูกค้าโอนสัญญาไม่ได้หากเราไม่ยินยอมเป็นลายลักษณ์อักษร Haliviq ใช้ผู้รับเหมาช่วงได้และยังรับผิดชอบงานของผู้รับเหมานั้น', 'การแจ้งอย่างเป็นทางการ: ต้องทำเป็นลายลักษณ์อักษร และส่งไปยังอีเมลหรือที่อยู่ตามที่ระบุในสัญญาหรือหัวข้อติดต่อเราด้านล่าง', 'ภาษา: ข้อกำหนดนี้จัดทำเป็นภาษาไทยและอังกฤษ หากไม่ตรงกัน ให้ถือตามฉบับภาษาไทย'] },
  { title: '23. การเปลี่ยนแปลงข้อกำหนด', body: 'เราอาจปรับปรุงข้อกำหนดการให้บริการนี้เป็นครั้งคราว หากมีการเปลี่ยนแปลงสำคัญ จะแสดงผ่านวันที่ปรับปรุงล่าสุดในหน้านี้ หากท่านใช้เว็บไซต์หรือบริการของเราต่อหลังการเปลี่ยนแปลงมีผล ถือว่าท่านยอมรับข้อกำหนดที่ปรับปรุงแล้ว การเปลี่ยนแปลงไม่กระทบเงื่อนไขของสัญญาที่ลงนามแล้ว' },
  { title: '24. ติดต่อเรา', body: 'หากมีคำถามเกี่ยวกับข้อกำหนดการให้บริการฉบับนี้ ติดต่อเราได้ที่ info@haliviq.com หรือส่งจดหมายมาที่ บริษัท ฮาลิวิค จำกัด 111 ถนนสุขุมวิท แขวงบางจาก เขตพระโขนง กรุงเทพฯ 10260' },
]

export default function Page({ params }: { params: { lang: Lang } }) {
  const lang = (params.lang === 'en' ? 'en' : 'th') as Lang
  const isEN = lang === 'en'
  const intro = isEN
    ? 'These Terms of Service explain the rules for using the Haliviq website and for working with us. Please read them together with our Privacy Policy and Cookie Policy. Where we have signed a project contract with you, that contract takes precedence for the engagement.'
    : 'ข้อกำหนดการให้บริการนี้อธิบายกติกาการใช้เว็บไซต์ Haliviq และการทำงานร่วมกับเรา โปรดอ่านควบคู่กับนโยบายความเป็นส่วนตัวและนโยบายคุกกี้ หากเรามีสัญญาโปรเจกต์ที่ลงนามกับท่านแล้ว ให้ถือสัญญานั้นเป็นหลักสำหรับงานนั้น'
  return <LegalPage lang={lang} title={isEN ? 'Terms of Service' : 'ข้อกำหนดการให้บริการ'} intro={intro} sections={isEN ? en : th} />
}
