import type { Metadata } from 'next'
import LegalPage, { type LegalSection } from '@/components/LegalPage'
import { type Lang } from '@/lib/i18n'

export async function generateStaticParams() {
  return [{ lang: 'th' }, { lang: 'en' }]
}

export async function generateMetadata({ params }: { params: { lang: Lang } }): Promise<Metadata> {
  const isEN = params.lang === 'en'
  const title = isEN ? 'Terms of Service | Haliviq' : 'ข้อกำหนดการให้บริการ | Haliviq'
  const description = isEN
    ? "The terms and conditions that govern your use of Haliviq's website and services."
    : 'ข้อกำหนดและเงื่อนไขการใช้งานเว็บไซต์และบริการของ Haliviq'
  const siteUrl = `https://haliviq.com/${params.lang}/terms`
  return { title, description, alternates: { canonical: siteUrl }, openGraph: { title, description, url: siteUrl } }
}

const en: LegalSection[] = [
  { title: '1. Acceptance of Terms', body: 'By accessing or using the Haliviq website, or by engaging Haliviq Co., Ltd. for any service, you agree to be bound by these Terms of Service. If you do not agree with any part of these terms, please do not use our website or services.', note: 'If you are accepting on behalf of a company or organisation, you confirm that you have authority to bind it.' },
  { title: '2. Definitions', items: ['"Haliviq", "we", "us" means Haliviq Co., Ltd., a company registered in Thailand.', '"Client" or "you" means the person or organisation that visits our website or engages us for services.', '"Services" means strategy, UX/UI design, website and application development, AI solutions, maintenance and related work.', '"Deliverables" means the designs, code, documents and other materials we create specifically for a Client under a signed proposal or contract.', '"Agreement" means the written proposal, statement of work or contract agreed for an engagement, together with these terms.'] },
  { title: '3. Our Services', body: 'Haliviq provides digital product strategy, UX/UI design, website and application development, and AI solutions. The scope, timeline, deliverables and fees of each engagement are defined in the Agreement, which takes precedence over these general terms for that engagement if the two conflict.' },
  { title: '4. Use of This Website', body: 'You may use our website for lawful purposes only. You agree not to:', items: ['attempt to gain unauthorised access to our systems, servers or data;', 'introduce malware, scrape the site at a rate that harms performance, or interfere with its operation;', 'use the site to send spam, unlawful, misleading or infringing material;', 'impersonate any person or misrepresent your affiliation with any person or organisation.'], note: 'We may suspend or restrict access to the website at any time without notice for maintenance, security or legal reasons.' },
  { title: '5. Enquiries and Form Submissions', body: 'Information you send through our contact form, email, LINE or WhatsApp is used to respond to your enquiry and prepare proposals, as described in our Privacy Policy. Submitting an enquiry does not create a contract; an engagement begins only when both parties sign or expressly accept a written Agreement.' },
  { title: '6. Proposals, Estimates and Change Requests', items: ['Proposals and estimates are valid for 30 days unless stated otherwise.', 'Work outside the agreed scope is handled as a change request, with any impact on fees and timeline agreed in writing before the work begins.', 'Timelines depend on timely Client feedback, content and access; delays on the Client side may move delivery dates accordingly.', 'Each engagement includes the number of review rounds stated in the Agreement; additional rounds may be charged.'] },
  { title: '7. Client Responsibilities', body: 'Clients are responsible for providing timely feedback, necessary access and accurate information, and for ensuring that content, images, fonts, data and trademarks they supply are lawful and that they hold the rights to use them. Delays or scope changes caused by the Client may affect timelines and may incur additional fees as outlined in the relevant Agreement.' },
  { title: '8. Payment Terms', items: ['Fees, payment schedules and milestones are set out in each Agreement.', 'Unless otherwise agreed, invoices are due within 15 days of issue.', 'Fees are exclusive of value-added tax (VAT) and withholding tax unless stated otherwise.', 'Overdue amounts may incur interest at the maximum rate permitted by Thai law.', 'Haliviq may pause work on overdue accounts, and withhold delivery or transfer of Deliverables, until payment is received.'] },
  { title: '9. Acceptance and Warranty Period', body: 'Deliverables are considered accepted when the Client approves them in writing, or if no written feedback is received within 7 business days of delivery. Unless the Agreement states otherwise, we will fix defects that do not conform to the agreed specification, reported within 30 days of acceptance, at no additional charge. Ongoing maintenance, hosting and new features are provided only under a separate maintenance or change agreement.' },
  { title: '10. Intellectual Property', body: 'Unless otherwise agreed in a signed contract, ownership of custom code, designs and other Deliverables created specifically for a Client transfers to that Client upon full payment.', items: ['Haliviq retains ownership of its pre-existing tools, frameworks, libraries, templates and general know-how, and grants the Client a non-exclusive, perpetual licence to use them as part of the Deliverables.', 'Haliviq may reuse non-confidential, non-client-specific components in future projects.', 'Until full payment is received, the Client holds only a limited licence to use the Deliverables.'] },
  { title: '11. Third-Party Tools and Open-Source Software', body: 'Our work may incorporate third-party services, libraries, fonts, stock assets, cloud platforms and open-source software. These remain subject to their own licences and terms, which the Client agrees to comply with. Fees charged by third parties (for example hosting, domains, paid plug-ins, API usage and licences) are the Client\'s responsibility unless the Agreement states otherwise.' },
  { title: '12. AI-Assisted Work and AI Solutions', body: 'We may use AI tools to assist with research, design, code and content, always under human review. For AI solutions we build for you:', items: ['AI outputs can be inaccurate, incomplete or biased and should be reviewed by a qualified person before being relied on for important decisions.', 'The Client is responsible for the lawful use of AI features, including the data they provide to the system and how outputs are used.', 'We do not use Client confidential data to train public AI models without the Client\'s written consent.', 'Model providers\' terms and usage policies apply to the AI services integrated into the solution.'] },
  { title: '13. Confidentiality', body: 'Both parties agree to keep confidential any non-public business, technical or financial information disclosed during an engagement, and to use it only for the purposes of that engagement. This obligation does not apply to information that is public through no fault of the recipient, already known to it, independently developed, or required to be disclosed by law. A separate Non-Disclosure Agreement (NDA) is available on request before any sensitive information is shared.' },
  { title: '14. Portfolio and Publicity', body: 'Unless the Client objects in writing or the Agreement says otherwise, Haliviq may display the project name, the Client\'s name and logo, and non-confidential screenshots or descriptions of the Deliverables in our portfolio, case studies and marketing materials. We will not disclose confidential information or credentials.' },
  { title: '15. Personal Data', body: 'Each party will comply with applicable data protection laws, including Thailand\'s Personal Data Protection Act B.E. 2562 (2019). Where we process personal data on a Client\'s behalf, we will do so only on the Client\'s documented instructions and under a data processing agreement where required. See our Privacy Policy for how we handle data collected through our own website and business dealings.' },
  { title: '16. Warranties and Disclaimer', body: 'We provide our Services with reasonable skill and care in line with industry standards. Except as expressly stated in the Agreement, and to the extent permitted by law, the website and Services are provided "as is" without warranties of any kind, including fitness for a particular purpose, uninterrupted or error-free operation, or specific business results such as traffic, rankings or revenue.' },
  { title: '17. Limitation of Liability', body: 'To the maximum extent permitted by law, Haliviq\'s total liability arising from any engagement is limited to the fees paid for the specific Service giving rise to the claim, and we are not liable for indirect, incidental, special or consequential damages, loss of profit, loss of data or loss of goodwill. Nothing in these terms limits liability that cannot be limited by law, such as for fraud or wilful misconduct.' },
  { title: '18. Indemnification', body: 'The Client agrees to indemnify Haliviq against third-party claims, losses and reasonable costs arising from content, data or materials the Client supplies, or from the Client\'s use of the Deliverables in breach of law or these terms. Haliviq will likewise indemnify the Client against third-party claims that Deliverables created solely by Haliviq infringe that party\'s intellectual property rights, provided the Client notifies us promptly and allows us to control the defence.' },
  { title: '19. Termination', body: 'Either party may terminate an active engagement in accordance with the notice period in the Agreement, or immediately if the other party materially breaches it and fails to remedy the breach within 14 days of written notice. On termination, the Client pays for work completed and non-cancellable costs incurred up to the termination date, and we will deliver work in progress once all amounts due are paid. Sections that by their nature should survive (intellectual property, confidentiality, payment, liability, governing law) continue after termination.' },
  { title: '20. Force Majeure', body: 'Neither party is liable for delay or failure to perform caused by events beyond its reasonable control, including natural disasters, epidemics, war, civil unrest, government action, power or internet outages, or failures of third-party platforms. The affected party will notify the other promptly and resume performance as soon as reasonably possible.' },
  { title: '21. Governing Law and Dispute Resolution', body: 'These Terms are governed by the laws of the Kingdom of Thailand. The parties will first try in good faith to resolve any dispute through discussion between senior representatives for at least 30 days. If unresolved, the dispute is subject to the exclusive jurisdiction of the courts of Thailand, unless a specific Agreement provides otherwise.' },
  { title: '22. General', items: ['Entire agreement: these terms and the Agreement are the entire understanding between the parties for the engagement and replace earlier discussions.', 'Severability: if any provision is found unenforceable, the rest remains in effect.', 'No waiver: failure to enforce a right is not a waiver of it.', 'Assignment: the Client may not assign the Agreement without our written consent; Haliviq may use subcontractors and remains responsible for their work.', 'Notices: formal notices must be in writing and sent to the email or postal address stated in the Agreement or in the Contact section below.', 'Language: these terms are provided in Thai and English; if the two differ, the Thai version prevails.'] },
  { title: '23. Changes to These Terms', body: 'We may update these Terms of Service from time to time. Material changes will be reflected by an updated "last updated" date on this page. Continued use of our website or services after changes take effect constitutes acceptance of the revised terms. Changes do not alter the terms of an Agreement already signed.' },
  { title: '24. Contact Us', body: 'If you have questions about these Terms of Service, please contact us at info@haliviq.com or write to Haliviq Co., Ltd., 111 Sukhumvit Rd, Bang Chak, Phra Khanong, Bangkok 10260, Thailand.' },
]

const th: LegalSection[] = [
  { title: '1. การยอมรับข้อกำหนด', body: 'การเข้าใช้งานเว็บไซต์ของ Haliviq หรือการว่าจ้างบริษัท ฮาลิวิค จำกัด เพื่อรับบริการใดๆ ถือว่าท่านยอมรับที่จะผูกพันตามข้อกำหนดการให้บริการฉบับนี้ หากท่านไม่ยอมรับข้อกำหนดส่วนใดส่วนหนึ่ง โปรดงดใช้งานเว็บไซต์หรือบริการของเรา', note: 'หากท่านยอมรับในนามบริษัทหรือองค์กร ท่านยืนยันว่ามีอำนาจผูกพันองค์กรนั้น' },
  { title: '2. คำนิยาม', items: ['"Haliviq" "เรา" หมายถึง บริษัท ฮาลิวิค จำกัด ซึ่งจดทะเบียนในประเทศไทย', '"ลูกค้า" หรือ "ท่าน" หมายถึง บุคคลหรือองค์กรที่เข้าชมเว็บไซต์หรือว่าจ้างเราให้บริการ', '"บริการ" หมายถึง กลยุทธ์ การออกแบบ UX/UI การพัฒนาเว็บไซต์และแอปพลิเคชัน โซลูชัน AI การบำรุงรักษา และงานที่เกี่ยวข้อง', '"งานส่งมอบ" หมายถึง ดีไซน์ Code เอกสาร และวัสดุอื่นที่เราสร้างขึ้นเฉพาะสำหรับลูกค้าตามข้อเสนอหรือสัญญาที่ลงนาม', '"สัญญา" หมายถึง ข้อเสนอ ขอบเขตงาน (SOW) หรือสัญญาเป็นลายลักษณ์อักษรของแต่ละโปรเจกต์ ร่วมกับข้อกำหนดฉบับนี้'] },
  { title: '3. บริการของเรา', body: 'Haliviq ให้บริการด้านกลยุทธ์ผลิตภัณฑ์ดิจิทัล ออกแบบ UX/UI พัฒนาเว็บไซต์และแอปพลิเคชัน และโซลูชัน AI ขอบเขตงาน ระยะเวลา สิ่งที่ส่งมอบ และค่าบริการของแต่ละโปรเจกต์กำหนดไว้ในสัญญา ซึ่งหากขัดแย้งกับข้อกำหนดทั่วไปนี้ ให้ใช้สัญญาเป็นหลักสำหรับโปรเจกต์นั้น' },
  { title: '4. การใช้งานเว็บไซต์', body: 'ท่านใช้เว็บไซต์ของเราได้เพื่อวัตถุประสงค์ที่ชอบด้วยกฎหมายเท่านั้น และตกลงว่าจะไม่:', items: ['พยายามเข้าถึงระบบ เซิร์ฟเวอร์ หรือข้อมูลของเราโดยไม่ได้รับอนุญาต', 'นำมัลแวร์เข้าสู่ระบบ ดึงข้อมูลเว็บไซต์ในระดับที่กระทบประสิทธิภาพ หรือรบกวนการทำงานของเว็บไซต์', 'ใช้เว็บไซต์เพื่อส่งสแปม หรือเนื้อหาที่ผิดกฎหมาย หลอกลวง หรือละเมิดสิทธิ์', 'แอบอ้างเป็นบุคคลอื่น หรือแสดงความสัมพันธ์กับบุคคลหรือองค์กรอื่นอันเป็นเท็จ'], note: 'เราอาจระงับหรือจำกัดการเข้าถึงเว็บไซต์ได้ทุกเมื่อโดยไม่ต้องแจ้งล่วงหน้า เพื่อการบำรุงรักษา ความปลอดภัย หรือเหตุผลทางกฎหมาย' },
  { title: '5. การสอบถามและการส่งแบบฟอร์ม', body: 'ข้อมูลที่ท่านส่งผ่านแบบฟอร์มติดต่อ อีเมล LINE หรือ WhatsApp จะถูกใช้เพื่อตอบกลับและจัดทำข้อเสนอ ตามที่ระบุในนโยบายความเป็นส่วนตัว การส่งข้อสอบถามไม่ถือเป็นการทำสัญญา การว่าจ้างจะเริ่มต้นเมื่อทั้งสองฝ่ายลงนามหรือยอมรับสัญญาเป็นลายลักษณ์อักษรอย่างชัดแจ้งเท่านั้น' },
  { title: '6. ข้อเสนอ ใบประเมินราคา และคำขอเปลี่ยนแปลง', items: ['ข้อเสนอและใบประเมินราคามีผล 30 วัน เว้นแต่ระบุไว้เป็นอย่างอื่น', 'งานนอกขอบเขตที่ตกลงจะดำเนินการเป็นคำขอเปลี่ยนแปลง (Change Request) โดยผลกระทบต่อค่าบริการและระยะเวลาต้องตกลงเป็นลายลักษณ์อักษรก่อนเริ่มงาน', 'ระยะเวลาขึ้นอยู่กับการให้ Feedback เนื้อหา และสิทธิ์การเข้าถึงจากลูกค้าอย่างทันท่วงที ความล่าช้าจากฝั่งลูกค้าอาจเลื่อนกำหนดส่งมอบ', 'แต่ละโปรเจกต์รวมจำนวนรอบการแก้ไขตามที่ระบุในสัญญา การแก้ไขเพิ่มเติมอาจมีค่าใช้จ่าย'] },
  { title: '7. ความรับผิดชอบของลูกค้า', body: 'ลูกค้ามีหน้าที่ให้ Feedback สิทธิ์การเข้าถึง และข้อมูลที่ถูกต้องอย่างทันท่วงที และรับรองว่าเนื้อหา รูปภาพ ฟอนต์ ข้อมูล และเครื่องหมายการค้าที่ลูกค้าจัดหาให้ชอบด้วยกฎหมายและลูกค้ามีสิทธิ์ใช้งาน ความล่าช้าหรือการเปลี่ยนขอบเขตที่เกิดจากลูกค้าอาจกระทบ Timeline และอาจมีค่าใช้จ่ายเพิ่มเติมตามที่ระบุในสัญญา' },
  { title: '8. เงื่อนไขการชำระเงิน', items: ['ค่าบริการ กำหนดการชำระเงิน และ Milestone ระบุไว้ในสัญญาของแต่ละโปรเจกต์', 'เว้นแต่ตกลงเป็นอย่างอื่น ใบแจ้งหนี้มีกำหนดชำระภายใน 15 วันนับจากวันที่ออก', 'ค่าบริการยังไม่รวมภาษีมูลค่าเพิ่ม (VAT) และภาษีหัก ณ ที่จ่าย เว้นแต่ระบุไว้เป็นอย่างอื่น', 'ยอดค้างชำระอาจมีดอกเบี้ยในอัตราสูงสุดตามที่กฎหมายไทยอนุญาต', 'Haliviq อาจระงับงานชั่วคราว และชะลอการส่งมอบหรือโอนงานส่งมอบ หากมียอดค้างชำระ จนกว่าจะได้รับชำระเงิน'] },
  { title: '9. การตรวจรับงานและระยะเวลารับประกัน', body: 'งานส่งมอบถือว่าได้รับการตรวจรับเมื่อลูกค้าอนุมัติเป็นลายลักษณ์อักษร หรือเมื่อไม่ได้รับ Feedback เป็นลายลักษณ์อักษรภายใน 7 วันทำการนับจากวันส่งมอบ เว้นแต่สัญญาจะระบุเป็นอย่างอื่น เราจะแก้ไขข้อบกพร่องที่ไม่เป็นไปตามข้อกำหนดที่ตกลงกัน ซึ่งแจ้งภายใน 30 วันนับจากการตรวจรับ โดยไม่คิดค่าใช้จ่ายเพิ่ม การบำรุงรักษา โฮสติ้ง และฟีเจอร์ใหม่จะให้บริการภายใต้สัญญาบำรุงรักษาหรือสัญญาเปลี่ยนแปลงแยกต่างหากเท่านั้น' },
  { title: '10. ทรัพย์สินทางปัญญา', body: 'เว้นแต่จะตกลงเป็นอย่างอื่นในสัญญาที่ลงนามร่วมกัน กรรมสิทธิ์ใน Code ดีไซน์ และงานส่งมอบอื่นที่สร้างขึ้นเฉพาะสำหรับลูกค้า จะโอนเป็นของลูกค้าเมื่อชำระเงินครบถ้วน', items: ['Haliviq ยังคงเป็นเจ้าของเครื่องมือ Framework ไลบรารี เทมเพลต และองค์ความรู้ทั่วไปที่มีอยู่ก่อน และให้สิทธิ์ลูกค้าใช้งานแบบไม่จำเพาะเจาะจงและไม่มีกำหนดเวลา ในฐานะส่วนหนึ่งของงานส่งมอบ', 'Haliviq สามารถนำส่วนประกอบที่ไม่เป็นความลับและไม่เฉพาะเจาะจงกับลูกค้าไปใช้ในโปรเจกต์อื่นได้', 'จนกว่าจะชำระเงินครบ ลูกค้ามีเพียงสิทธิ์จำกัดในการใช้งานงานส่งมอบ'] },
  { title: '11. เครื่องมือของบุคคลที่สามและซอฟต์แวร์โอเพนซอร์ส', body: 'งานของเราอาจใช้บริการ ไลบรารี ฟอนต์ สต็อกภาพ แพลตฟอร์มคลาวด์ และซอฟต์แวร์โอเพนซอร์สของบุคคลที่สาม ซึ่งอยู่ภายใต้ใบอนุญาตและข้อกำหนดของตนเอง และลูกค้าตกลงปฏิบัติตาม ค่าใช้จ่ายของบุคคลที่สาม (เช่น โฮสติ้ง โดเมน ปลั๊กอินแบบชำระเงิน การใช้ API และลิขสิทธิ์) เป็นความรับผิดชอบของลูกค้า เว้นแต่สัญญาจะระบุเป็นอย่างอื่น' },
  { title: '12. งานที่ใช้ AI ช่วยและโซลูชัน AI', body: 'เราอาจใช้เครื่องมือ AI ช่วยงานวิจัย ดีไซน์ Code และเนื้อหา โดยมีมนุษย์ตรวจสอบเสมอ สำหรับโซลูชัน AI ที่เราพัฒนาให้ท่าน:', items: ['ผลลัพธ์จาก AI อาจไม่ถูกต้อง ไม่ครบถ้วน หรือมีอคติ ควรให้ผู้เชี่ยวชาญตรวจสอบก่อนนำไปใช้ตัดสินใจเรื่องสำคัญ', 'ลูกค้ามีหน้าที่ใช้ฟีเจอร์ AI อย่างชอบด้วยกฎหมาย รวมถึงข้อมูลที่ป้อนเข้าระบบและการนำผลลัพธ์ไปใช้', 'เราไม่ใช้ข้อมูลที่เป็นความลับของลูกค้าเพื่อฝึกโมเดล AI สาธารณะ หากไม่ได้รับความยินยอมเป็นลายลักษณ์อักษร', 'ข้อกำหนดและนโยบายการใช้งานของผู้ให้บริการโมเดลมีผลกับบริการ AI ที่ผนวกอยู่ในโซลูชัน'] },
  { title: '13. การรักษาความลับ', body: 'ทั้งสองฝ่ายตกลงรักษาความลับของข้อมูลทางธุรกิจ เทคนิค หรือการเงินที่ไม่เปิดเผยต่อสาธารณะซึ่งเปิดเผยระหว่างการทำงานร่วมกัน และใช้เพื่อวัตถุประสงค์ของโปรเจกต์นั้นเท่านั้น ภาระนี้ไม่ครอบคลุมข้อมูลที่เป็นสาธารณะโดยมิใช่ความผิดของผู้รับ ข้อมูลที่ผู้รับทราบอยู่แล้ว ที่พัฒนาขึ้นโดยอิสระ หรือที่กฎหมายกำหนดให้เปิดเผย สามารถขอทำข้อตกลงไม่เปิดเผยข้อมูล (NDA) แยกต่างหากได้ก่อนแบ่งปันข้อมูลที่อ่อนไหว' },
  { title: '14. ผลงานและการเผยแพร่', body: 'เว้นแต่ลูกค้าคัดค้านเป็นลายลักษณ์อักษรหรือสัญญาระบุเป็นอย่างอื่น Haliviq สามารถแสดงชื่อโปรเจกต์ ชื่อและโลโก้ลูกค้า และภาพหน้าจอหรือคำอธิบายงานส่งมอบที่ไม่เป็นความลับในผลงาน กรณีศึกษา และสื่อการตลาดของเรา โดยจะไม่เปิดเผยข้อมูลลับหรือรหัสผ่านใดๆ' },
  { title: '15. ข้อมูลส่วนบุคคล', body: 'แต่ละฝ่ายจะปฏิบัติตามกฎหมายคุ้มครองข้อมูลส่วนบุคคลที่เกี่ยวข้อง รวมถึงพระราชบัญญัติคุ้มครองข้อมูลส่วนบุคคล พ.ศ. 2562 (PDPA) หากเราประมวลผลข้อมูลส่วนบุคคลในนามลูกค้า จะดำเนินการตามคำสั่งที่เป็นลายลักษณ์อักษรของลูกค้าเท่านั้น และภายใต้ข้อตกลงประมวลผลข้อมูลเมื่อกฎหมายกำหนด ดูนโยบายความเป็นส่วนตัวของเราสำหรับการจัดการข้อมูลที่เก็บผ่านเว็บไซต์และการติดต่อทางธุรกิจของเรา' },
  { title: '16. การรับประกันและข้อสงวนสิทธิ์', body: 'เราให้บริการด้วยความชำนาญและความระมัดระวังตามมาตรฐานอุตสาหกรรม เว้นแต่ที่ระบุไว้ชัดแจ้งในสัญญา และภายใต้ขอบเขตที่กฎหมายอนุญาต เว็บไซต์และบริการให้ "ตามสภาพ" โดยไม่มีการรับประกันใดๆ รวมถึงความเหมาะสมเพื่อวัตถุประสงค์เฉพาะ การทำงานโดยไม่หยุดชะงักหรือปราศจากข้อผิดพลาด หรือผลลัพธ์ทางธุรกิจเฉพาะ เช่น ปริมาณผู้เข้าชม อันดับ หรือรายได้' },
  { title: '17. ข้อจำกัดความรับผิด', body: 'ภายใต้ขอบเขตสูงสุดที่กฎหมายอนุญาต ความรับผิดรวมของ Haliviq ที่เกิดจากการทำงานใดๆ จะจำกัดอยู่ที่จำนวนค่าบริการที่ได้รับชำระสำหรับบริการที่เกี่ยวข้องกับข้อเรียกร้องนั้น และเราจะไม่รับผิดต่อความเสียหายทางอ้อม โดยบังเอิญ เป็นพิเศษ หรือที่เป็นผลสืบเนื่อง การสูญเสียกำไร ข้อมูล หรือชื่อเสียง ข้อกำหนดนี้ไม่จำกัดความรับผิดที่กฎหมายไม่อนุญาตให้จำกัด เช่น กรณีฉ้อโกงหรือจงใจกระทำผิด' },
  { title: '18. การชดใช้ค่าเสียหาย', body: 'ลูกค้าตกลงชดใช้ให้ Haliviq สำหรับข้อเรียกร้อง ความเสียหาย และค่าใช้จ่ายอันสมควรจากบุคคลที่สาม ที่เกิดจากเนื้อหา ข้อมูล หรือวัสดุที่ลูกค้าจัดหา หรือจากการที่ลูกค้าใช้งานส่งมอบฝ่าฝืนกฎหมายหรือข้อกำหนดนี้ ในทำนองเดียวกัน Haliviq จะชดใช้ให้ลูกค้าสำหรับข้อเรียกร้องจากบุคคลที่สามว่างานส่งมอบที่ Haliviq สร้างขึ้นโดยลำพังละเมิดทรัพย์สินทางปัญญา โดยลูกค้าต้องแจ้งเราโดยเร็วและให้เราเป็นผู้ควบคุมการต่อสู้คดี' },
  { title: '19. การยกเลิกสัญญา', body: 'คู่สัญญาฝ่ายใดฝ่ายหนึ่งสามารถยกเลิกโปรเจกต์ที่กำลังดำเนินอยู่ได้ตามระยะเวลาแจ้งล่วงหน้าในสัญญา หรือยกเลิกทันทีหากอีกฝ่ายผิดสัญญาอย่างมีนัยสำคัญและไม่แก้ไขภายใน 14 วันนับจากได้รับหนังสือแจ้ง เมื่อยกเลิก ลูกค้าชำระค่างานที่ทำเสร็จและค่าใช้จ่ายที่ยกเลิกไม่ได้จนถึงวันที่ยกเลิก และเราจะส่งมอบงานที่ทำค้างอยู่เมื่อได้รับชำระครบถ้วน ข้อกำหนดที่โดยสภาพควรมีผลต่อเนื่อง (ทรัพย์สินทางปัญญา การรักษาความลับ การชำระเงิน ความรับผิด กฎหมายที่ใช้บังคับ) ยังคงมีผลหลังยกเลิก' },
  { title: '20. เหตุสุดวิสัย', body: 'ทั้งสองฝ่ายไม่ต้องรับผิดต่อความล่าช้าหรือการไม่ปฏิบัติตามสัญญาที่เกิดจากเหตุการณ์เกินกว่าที่จะควบคุมได้ตามสมควร เช่น ภัยธรรมชาติ โรคระบาด สงคราม ความไม่สงบ การกระทำของรัฐ ไฟฟ้าหรืออินเทอร์เน็ตขัดข้อง หรือความล้มเหลวของแพลตฟอร์มบุคคลที่สาม ฝ่ายที่ได้รับผลกระทบจะแจ้งอีกฝ่ายโดยเร็วและกลับมาดำเนินการทันทีเมื่อสามารถทำได้' },
  { title: '21. กฎหมายที่ใช้บังคับและการระงับข้อพิพาท', body: 'ข้อกำหนดนี้อยู่ภายใต้บังคับกฎหมายแห่งราชอาณาจักรไทย คู่สัญญาจะพยายามระงับข้อพิพาทโดยสุจริตผ่านการเจรจาระหว่างผู้แทนระดับอาวุโสไม่น้อยกว่า 30 วันก่อน หากไม่สำเร็จ ข้อพิพาทจะอยู่ภายใต้เขตอำนาจศาลไทยแต่เพียงผู้เดียว เว้นแต่สัญญาเฉพาะจะกำหนดเป็นอย่างอื่น' },
  { title: '22. ข้อกำหนดทั่วไป', items: ['ข้อตกลงทั้งหมด: ข้อกำหนดนี้และสัญญาเป็นข้อตกลงทั้งหมดระหว่างคู่สัญญาสำหรับโปรเจกต์ และแทนที่การเจรจาก่อนหน้า', 'ความสมบูรณ์ของข้อกำหนด: หากข้อใดบังคับใช้ไม่ได้ ข้อที่เหลือยังคงมีผล', 'การไม่ใช้สิทธิ์: การไม่ใช้สิทธิ์ในครั้งใดไม่ถือเป็นการสละสิทธิ์นั้น', 'การโอนสิทธิ์: ลูกค้าไม่สามารถโอนสัญญาโดยไม่ได้รับความยินยอมเป็นลายลักษณ์อักษรจากเรา Haliviq อาจใช้ผู้รับเหมาช่วงและยังคงรับผิดชอบงานของผู้รับเหมา', 'การแจ้งเตือน: หนังสือแจ้งอย่างเป็นทางการต้องทำเป็นลายลักษณ์อักษร และส่งไปยังอีเมลหรือที่อยู่ตามที่ระบุในสัญญาหรือหัวข้อติดต่อเราด้านล่าง', 'ภาษา: ข้อกำหนดนี้จัดทำเป็นภาษาไทยและอังกฤษ หากแตกต่างกัน ให้ถือตามฉบับภาษาไทย'] },
  { title: '23. การเปลี่ยนแปลงข้อกำหนด', body: 'เราอาจปรับปรุงข้อกำหนดการให้บริการนี้เป็นครั้งคราว การเปลี่ยนแปลงที่มีนัยสำคัญจะสะท้อนผ่านวันที่ปรับปรุงล่าสุดในหน้านี้ การใช้งานเว็บไซต์หรือบริการของเราต่อไปหลังการเปลี่ยนแปลงมีผล ถือว่าท่านยอมรับข้อกำหนดที่ปรับปรุงแล้ว การเปลี่ยนแปลงไม่กระทบเงื่อนไขของสัญญาที่ลงนามแล้ว' },
  { title: '24. ติดต่อเรา', body: 'หากท่านมีคำถามเกี่ยวกับข้อกำหนดการให้บริการฉบับนี้ โปรดติดต่อเราที่ info@haliviq.com หรือส่งจดหมายมาที่ บริษัท ฮาลิวิค จำกัด 111 ถนนสุขุมวิท แขวงบางจาก เขตพระโขนง กรุงเทพฯ 10260' },
]

export default function Page({ params }: { params: { lang: Lang } }) {
  const lang = (params.lang === 'en' ? 'en' : 'th') as Lang
  const isEN = lang === 'en'
  const intro = isEN
    ? 'These Terms of Service explain the rules for using the Haliviq website and for working with us. Please read them together with our Privacy Policy and Cookie Policy. Where we have signed a project contract with you, that contract takes precedence for the engagement.'
    : 'ข้อกำหนดการให้บริการนี้อธิบายกฎการใช้งานเว็บไซต์ Haliviq และการทำงานร่วมกับเรา โปรดอ่านควบคู่กับนโยบายความเป็นส่วนตัวและนโยบายคุกกี้ หากเรามีสัญญาโปรเจกต์ที่ลงนามกับท่าน ให้ถือสัญญานั้นเป็นหลักสำหรับงานดังกล่าว'
  return <LegalPage lang={lang} title={isEN ? 'Terms of Service' : 'ข้อกำหนดการให้บริการ'} intro={intro} sections={isEN ? en : th} />
}
